/*
 jQuery JavaScript Library v3.2.1
 https://jquery.com/

 Includes Sizzle.js
 https://sizzlejs.com/

 Copyright JS Foundation and other contributors
 Released under the MIT license
 https://jquery.org/license

 Date: 2017-03-20T18:59Z
 Sizzle CSS Selector Engine v2.3.3
 https://sizzlejs.com/

 Copyright jQuery Foundation and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2016-08-08
  //MIK hai aggiunto controllo su escludeFromSubmit classe
*/
(function(p,W){"object"===typeof module&&"object"===typeof module.exports?module.exports=p.document?W(p,!0):function(p){if(!p.document)throw Error("jQuery requires a window with a document");return W(p)}:W(p)})("undefined"!==typeof window?window:this,function(p,W){function $a(a,b){b=b||r;var d=b.createElement("script");d.text=a;b.head.appendChild(d).parentNode.removeChild(d)}function Ma(a){var b=!!a&&"length"in a&&a.length,d=c.type(a);return"function"===d||c.isWindow(a)?!1:"array"===d||0===b||"number"===
typeof b&&0<b&&b-1 in a}function F(a,b){return a.nodeName&&a.nodeName.toLowerCase()===b.toLowerCase()}function Na(a,b,d){if(c.isFunction(b))return c.grep(a,function(a,c){return!!b.call(a,c,a)!==d});if(b.nodeType)return c.grep(a,function(a){return a===b!==d});if("string"!==typeof b)return c.grep(a,function(a){return-1<sa.call(b,a)!==d});if(Qb.test(b))return c.filter(b,a,d);b=c.filter(b,a);return c.grep(a,function(a){return-1<sa.call(b,a)!==d&&1===a.nodeType})}function ab(a,b){for(;(a=a[b])&&1!==a.nodeType;);
return a}function Rb(a){var b={};c.each(a.match(M)||[],function(a,c){b[c]=!0});return b}function ia(a){return a}function ja(a){throw a;}function bb(a,b,d,e){var f;try{a&&c.isFunction(f=a.promise)?f.call(a).done(b).fail(d):a&&c.isFunction(f=a.then)?f.call(a,b,d):b.apply(void 0,[a].slice(e))}catch(g){d.apply(void 0,[g])}}function aa(){r.removeEventListener("DOMContentLoaded",aa);p.removeEventListener("load",aa);c.ready()}function ba(){this.expando=c.expando+ba.uid++}function cb(a,b,d){if(void 0===d&&
1===a.nodeType)if(d="data-"+b.replace(Sb,"-$&").toLowerCase(),d=a.getAttribute(d),"string"===typeof d){try{var c=d;d="true"===c?!0:"false"===c?!1:"null"===c?null:c===+c+""?+c:Tb.test(c)?JSON.parse(c):c}catch(f){}E.set(a,b,d)}else d=void 0;return d}function db(a,b,d,e){var f=1,g=20,h=e?function(){return e.cur()}:function(){return c.css(a,b,"")},l=h(),k=d&&d[3]||(c.cssNumber[b]?"":"px"),m=(c.cssNumber[b]||"px"!==k&&+l)&&ka.exec(c.css(a,b));if(m&&m[3]!==k){k=k||m[3];d=d||[];m=+l||1;do f=f||".5",m/=f,
c.style(a,b,m+k);while(f!==(f=h()/l)&&1!==f&&--g)}if(d){m=+m||+l||0;var n=d[1]?m+(d[1]+1)*d[2]:+d[2];e&&(e.unit=k,e.start=m,e.end=n)}return n}function la(a,b){for(var d,e,f=[],g=0,h=a.length;g<h;g++)if(e=a[g],e.style)if(d=e.style.display,b){if("none"===d&&(f[g]=v.get(e,"display")||null,f[g]||(e.style.display="")),""===e.style.display&&ta(e)){d=g;var l=e.ownerDocument;e=e.nodeName;var k=eb[e];k||(l=l.body.appendChild(l.createElement(e)),k=c.css(l,"display"),l.parentNode.removeChild(l),"none"===k&&
(k="block"),eb[e]=k);l=k;f[d]=l}}else"none"!==d&&(f[g]="none",v.set(e,"display",d));for(g=0;g<h;g++)null!=f[g]&&(a[g].style.display=f[g]);return a}function z(a,b){var d="undefined"!==typeof a.getElementsByTagName?a.getElementsByTagName(b||"*"):"undefined"!==typeof a.querySelectorAll?a.querySelectorAll(b||"*"):[];return void 0===b||b&&F(a,b)?c.merge([a],d):d}function Oa(a,b){for(var d=0,c=a.length;d<c;d++)v.set(a[d],"globalEval",!b||v.get(b[d],"globalEval"))}function fb(a,b,d,e,f){for(var g,h,l,k=
b.createDocumentFragment(),m=[],n=0,q=a.length;n<q;n++)if((g=a[n])||0===g)if("object"===c.type(g))c.merge(m,g.nodeType?[g]:g);else if(Ub.test(g)){h=h||k.appendChild(b.createElement("div"));l=(gb.exec(g)||["",""])[1].toLowerCase();l=N[l]||N._default;h.innerHTML=l[1]+c.htmlPrefilter(g)+l[2];for(l=l[0];l--;)h=h.lastChild;c.merge(m,h.childNodes);h=k.firstChild;h.textContent=""}else m.push(b.createTextNode(g));k.textContent="";for(n=0;g=m[n++];)if(e&&-1<c.inArray(g,e))f&&f.push(g);else if(a=c.contains(g.ownerDocument,
g),h=z(k.appendChild(g),"script"),a&&Oa(h),d)for(l=0;g=h[l++];)hb.test(g.type||"")&&d.push(g);return k}function ya(){return!0}function ma(){return!1}function ib(){try{return r.activeElement}catch(a){}}function Pa(a,b,d,e,f,g){var h;if("object"===typeof b){"string"!==typeof d&&(e=e||d,d=void 0);for(h in b)Pa(a,h,d,e,b[h],g);return a}null==e&&null==f?(f=d,e=d=void 0):null==f&&("string"===typeof d?(f=e,e=void 0):(f=e,e=d,d=void 0));if(!1===f)f=ma;else if(!f)return a;if(1===g){var l=f;f=function(a){c().off(a);
return l.apply(this,arguments)};f.guid=l.guid||(l.guid=c.guid++)}return a.each(function(){c.event.add(this,b,f,e,d)})}function jb(a,b){return F(a,"table")&&F(11!==b.nodeType?b:b.firstChild,"tr")?c(">tbody",a)[0]||a:a}function Vb(a){a.type=(null!==a.getAttribute("type"))+"/"+a.type;return a}function Wb(a){var b=Xb.exec(a.type);b?a.type=b[1]:a.removeAttribute("type");return a}function kb(a,b){var d;if(1===b.nodeType){if(v.hasData(a)){var e=v.access(a);var f=v.set(b,e);if(e=e.events)for(g in delete f.handle,
f.events={},e)for(f=0,d=e[g].length;f<d;f++)c.event.add(b,g,e[g][f])}if(E.hasData(a)){var g=E.access(a);g=c.extend({},g);E.set(b,g)}}}function X(a,b,d,e){b=lb.apply([],b);var f,g=0,h=a.length,l=h-1,k=b[0],m=c.isFunction(k);if(m||1<h&&"string"===typeof k&&!t.checkClone&&Yb.test(k))return a.each(function(c){var f=a.eq(c);m&&(b[0]=k.call(this,c,f.html()));X(f,b,d,e)});if(h){var n=fb(b,a[0].ownerDocument,!1,a,e);var q=n.firstChild;1===n.childNodes.length&&(n=q);if(q||e){q=c.map(z(n,"script"),Vb);for(f=
q.length;g<h;g++){var w=n;g!==l&&(w=c.clone(w,!0,!0),f&&c.merge(q,z(w,"script")));d.call(a[g],w,g)}if(f)for(n=q[q.length-1].ownerDocument,c.map(q,Wb),g=0;g<f;g++)w=q[g],hb.test(w.type||"")&&!v.access(w,"globalEval")&&c.contains(n,w)&&(w.src?c._evalUrl&&c._evalUrl(w.src):$a(w.textContent.replace(Zb,""),n))}}return a}function mb(a,b,d){for(var e=b?c.filter(b,a):a,f=0;null!=(b=e[f]);f++)d||1!==b.nodeType||c.cleanData(z(b)),b.parentNode&&(d&&c.contains(b.ownerDocument,b)&&Oa(z(b,"script")),b.parentNode.removeChild(b));
return a}function na(a,b,d){var e=a.style;if(d=d||Da(a)){var f=d.getPropertyValue(b)||d[b];""!==f||c.contains(a.ownerDocument,a)||(f=c.style(a,b));if(!t.pixelMarginRight()&&Qa.test(f)&&nb.test(b)){a=e.width;b=e.minWidth;var g=e.maxWidth;e.minWidth=e.maxWidth=e.width=f;f=d.width;e.width=a;e.minWidth=b;e.maxWidth=g}}return void 0!==f?f+"":f}function ob(a,b){return{get:function(){if(a())delete this.get;else return(this.get=b).apply(this,arguments)}}}function pb(a){var b=c.cssProps[a];if(!b){var b=c.cssProps;
a:{var d=a;if(!(d in qb)){for(var e=d[0].toUpperCase()+d.slice(1),f=rb.length;f--;)if(d=rb[f]+e,d in qb)break a;d=void 0}}b=b[a]=d||a}return b}function sb(a,b,d){return(a=ka.exec(b))?Math.max(0,a[2]-(d||0))+(a[3]||"px"):b}function tb(a,b,d,e,f){var g=0;for(b=d===(e?"border":"content")?4:"width"===b?1:0;4>b;b+=2)"margin"===d&&(g+=c.css(a,d+Z[b],!0,f)),e?("content"===d&&(g-=c.css(a,"padding"+Z[b],!0,f)),"margin"!==d&&(g-=c.css(a,"border"+Z[b]+"Width",!0,f))):(g+=c.css(a,"padding"+Z[b],!0,f),"padding"!==
d&&(g+=c.css(a,"border"+Z[b]+"Width",!0,f)));return g}function ub(a,b,d){var e=Da(a),f=na(a,b,e),g="border-box"===c.css(a,"boxSizing",!1,e);if(Qa.test(f))return f;var h=g&&(t.boxSizingReliable()||f===a.style[b]);"auto"===f&&(f=a["offset"+b[0].toUpperCase()+b.slice(1)]);f=parseFloat(f)||0;return f+tb(a,b,d||(g?"border":"content"),h,e)+"px"}function H(a,b,d,c,f){return new H.prototype.init(a,b,d,c,f)}function Ra(){Ea&&(!1===r.hidden&&p.requestAnimationFrame?p.requestAnimationFrame(Ra):p.setTimeout(Ra,
c.fx.interval),c.fx.tick())}function vb(){p.setTimeout(function(){oa=void 0});return oa=c.now()}function Fa(a,b){var d=0,c={height:a};for(b=b?1:0;4>d;d+=2-b){var f=Z[d];c["margin"+f]=c["padding"+f]=a}b&&(c.opacity=c.width=a);return c}function wb(a,b,d){for(var c,f=(S.tweeners[b]||[]).concat(S.tweeners["*"]),g=0,h=f.length;g<h;g++)if(c=f[g].call(d,b,a))return c}function $b(a,b){var d,e;for(d in a){var f=c.camelCase(d);var g=b[f];var h=a[d];Array.isArray(h)&&(g=h[1],h=a[d]=h[0]);d!==f&&(a[f]=h,delete a[d]);
if((e=c.cssHooks[f])&&"expand"in e)for(d in h=e.expand(h),delete a[f],h)d in a||(a[d]=h[d],b[d]=g);else b[f]=g}}function S(a,b,d){var e,f=0,g=S.prefilters.length,h=c.Deferred().always(function(){delete l.elem}),l=function(){if(e)return!1;for(var b=oa||vb(),b=Math.max(0,k.startTime+k.duration-b),d=1-(b/k.duration||0),c=0,f=k.tweens.length;c<f;c++)k.tweens[c].run(d);h.notifyWith(a,[k,d,b]);if(1>d&&f)return b;f||h.notifyWith(a,[k,1,0]);h.resolveWith(a,[k]);return!1},k=h.promise({elem:a,props:c.extend({},
b),opts:c.extend(!0,{specialEasing:{},easing:c.easing._default},d),originalProperties:b,originalOptions:d,startTime:oa||vb(),duration:d.duration,tweens:[],createTween:function(b,d){var e=c.Tween(a,k.opts,b,d,k.opts.specialEasing[b]||k.opts.easing);k.tweens.push(e);return e},stop:function(b){var d=0,c=b?k.tweens.length:0;if(e)return this;for(e=!0;d<c;d++)k.tweens[d].run(1);b?(h.notifyWith(a,[k,1,0]),h.resolveWith(a,[k,b])):h.rejectWith(a,[k,b]);return this}});d=k.props;for($b(d,k.opts.specialEasing);f<
g;f++)if(b=S.prefilters[f].call(k,a,d,k.opts))return c.isFunction(b.stop)&&(c._queueHooks(k.elem,k.opts.queue).stop=c.proxy(b.stop,b)),b;c.map(d,wb,k);c.isFunction(k.opts.start)&&k.opts.start.call(a,k);k.progress(k.opts.progress).done(k.opts.done,k.opts.complete).fail(k.opts.fail).always(k.opts.always);c.fx.timer(c.extend(l,{elem:a,anim:k,queue:k.opts.queue}));return k}function B(a){return(a.match(M)||[]).join(" ")}function ca(a){return a.getAttribute&&a.getAttribute("class")||""}function Sa(a,b,
d,e){var f;if(Array.isArray(b))c.each(b,function(b,c){d||ac.test(a)?e(a,c):Sa(a+"["+("object"===typeof c&&null!=c?b:"")+"]",c,d,e)});else if(d||"object"!==c.type(b))e(a,b);else for(f in b)Sa(a+"["+f+"]",b[f],d,e)}function xb(a){return function(b,d){"string"!==typeof b&&(d=b,b="*");var e,f=0,g=b.toLowerCase().match(M)||[];if(c.isFunction(d))for(;e=g[f++];)"+"===e[0]?(e=e.slice(1)||"*",(a[e]=a[e]||[]).unshift(d)):(a[e]=a[e]||[]).push(d)}}function yb(a,b,d,e){function f(l){var k;g[l]=!0;c.each(a[l]||
[],function(a,c){var l=c(b,d,e);if("string"===typeof l&&!h&&!g[l])return b.dataTypes.unshift(l),f(l),!1;if(h)return!(k=l)});return k}var g={},h=a===Ta;return f(b.dataTypes[0])||!g["*"]&&f("*")}function Ua(a,b){var d,e,f=c.ajaxSettings.flatOptions||{};for(d in b)void 0!==b[d]&&((f[d]?a:e||(e={}))[d]=b[d]);e&&c.extend(!0,a,e);return a}var T=[],r=p.document,bc=Object.getPrototypeOf,da=T.slice,lb=T.concat,Va=T.push,sa=T.indexOf,Ga={},zb=Ga.toString,Ha=Ga.hasOwnProperty,Ab=Ha.toString,cc=Ab.call(Object),
t={},c=function(a,b){return new c.fn.init(a,b)},dc=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,ec=/^-ms-/,fc=/-([a-z])/g,gc=function(a,b){return b.toUpperCase()};c.fn=c.prototype={jquery:"3.2.1",constructor:c,length:0,toArray:function(){return da.call(this)},get:function(a){return null==a?da.call(this):0>a?this[a+this.length]:this[a]},pushStack:function(a){a=c.merge(this.constructor(),a);a.prevObject=this;return a},each:function(a){return c.each(this,a)},map:function(a){return this.pushStack(c.map(this,
function(b,d){return a.call(b,d,b)}))},slice:function(){return this.pushStack(da.apply(this,arguments))},first:function(){return this.eq(0)},last:function(){return this.eq(-1)},eq:function(a){var b=this.length;a=+a+(0>a?b:0);return this.pushStack(0<=a&&a<b?[this[a]]:[])},end:function(){return this.prevObject||this.constructor()},push:Va,sort:T.sort,splice:T.splice};c.extend=c.fn.extend=function(){var a,b,d,e=arguments[0]||{},f=1,g=arguments.length,h=!1;"boolean"===typeof e&&(h=e,e=arguments[f]||{},
f++);"object"===typeof e||c.isFunction(e)||(e={});f===g&&(e=this,f--);for(;f<g;f++)if(null!=(a=arguments[f]))for(b in a){var l=e[b];var k=a[b];e!==k&&(h&&k&&(c.isPlainObject(k)||(d=Array.isArray(k)))?(d?(d=!1,l=l&&Array.isArray(l)?l:[]):l=l&&c.isPlainObject(l)?l:{},e[b]=c.extend(h,l,k)):void 0!==k&&(e[b]=k))}return e};c.extend({expando:"jQuery"+("3.2.1"+Math.random()).replace(/\D/g,""),isReady:!0,error:function(a){throw Error(a);},noop:function(){},isFunction:function(a){return"function"===c.type(a)},
isWindow:function(a){return null!=a&&a===a.window},isNumeric:function(a){var b=c.type(a);return("number"===b||"string"===b)&&!isNaN(a-parseFloat(a))},isPlainObject:function(a){if(!a||"[object Object]"!==zb.call(a))return!1;a=bc(a);if(!a)return!0;a=Ha.call(a,"constructor")&&a.constructor;return"function"===typeof a&&Ab.call(a)===cc},isEmptyObject:function(a){for(var b in a)return!1;return!0},type:function(a){return null==a?a+"":"object"===typeof a||"function"===typeof a?Ga[zb.call(a)]||"object":typeof a},
globalEval:function(a){$a(a)},camelCase:function(a){return a.replace(ec,"ms-").replace(fc,gc)},each:function(a,b){var d,c=0;if(Ma(a))for(d=a.length;c<d&&!1!==b.call(a[c],c,a[c]);c++);else for(c in a)if(!1===b.call(a[c],c,a[c]))break;return a},trim:function(a){return null==a?"":(a+"").replace(dc,"")},makeArray:function(a,b){var d=b||[];null!=a&&(Ma(Object(a))?c.merge(d,"string"===typeof a?[a]:a):Va.call(d,a));return d},inArray:function(a,b,d){return null==b?-1:sa.call(b,a,d)},merge:function(a,b){for(var d=
+b.length,c=0,f=a.length;c<d;c++)a[f++]=b[c];a.length=f;return a},grep:function(a,b,d){for(var c=[],f=0,g=a.length,h=!d;f<g;f++)d=!b(a[f],f),d!==h&&c.push(a[f]);return c},map:function(a,b,d){var c,f=0,g=[];if(Ma(a))for(c=a.length;f<c;f++){var h=b(a[f],f,d);null!=h&&g.push(h)}else for(f in a)h=b(a[f],f,d),null!=h&&g.push(h);return lb.apply([],g)},guid:1,proxy:function(a,b){if("string"===typeof b){var d=a[b];b=a;a=d}if(c.isFunction(a)){var e=da.call(arguments,2);d=function(){return a.apply(b||this,
e.concat(da.call(arguments)))};d.guid=a.guid=a.guid||c.guid++;return d}},now:Date.now,support:t});"function"===typeof Symbol&&(c.fn[Symbol.iterator]=T[Symbol.iterator]);c.each("Boolean Number String Function Array Date RegExp Object Error Symbol".split(" "),function(a,b){Ga["[object "+b+"]"]=b.toLowerCase()});var ha=function(a){function b(a,b,c,d){var e,f,g,C,h=b&&b.ownerDocument,u=b?b.nodeType:9;c=c||[];if("string"!==typeof a||!a||1!==u&&9!==u&&11!==u)return c;if(!d&&((b?b.ownerDocument||b:G)!==
x&&ua(b),b=b||x,U)){if(11!==u&&(C=sa.exec(a)))if(e=C[1])if(9===u)if(f=b.getElementById(e)){if(f.id===e)return c.push(f),c}else return c;else{if(h&&(f=h.getElementById(e))&&Ba(b,f)&&f.id===e)return c.push(f),c}else{if(C[2])return pa.apply(c,b.getElementsByTagName(a)),c;if((e=C[3])&&I.getElementsByClassName&&b.getElementsByClassName)return pa.apply(c,b.getElementsByClassName(e)),c}if(!(!I.qsa||Ia[a+" "]||P&&P.test(a))){if(1!==u){h=b;var K=a}else if("object"!==b.nodeName.toLowerCase()){(g=b.getAttribute("id"))?
g=g.replace(ka,na):b.setAttribute("id",g=A);f=aa(a);for(e=f.length;e--;)f[e]="#"+g+" "+p(f[e]);K=f.join(",");h=ba.test(a)&&q(b.parentNode)||b}if(K)try{return pa.apply(c,h.querySelectorAll(K)),c}catch(Lc){}finally{g===A&&b.removeAttribute("id")}}}return ya(a.replace(T,"$1"),b,c,d)}function d(){function a(c,d){b.push(c+" ")>D.cacheLength&&delete a[b.shift()];return a[c+" "]=d}var b=[];return a}function c(a){a[A]=!0;return a}function f(a){var b=x.createElement("fieldset");try{return!!a(b)}catch(u){return!1}finally{b.parentNode&&
b.parentNode.removeChild(b)}}function g(a,b){for(var c=a.split("|"),d=c.length;d--;)D.attrHandle[c[d]]=b}function h(a,b){var c=b&&a,d=c&&1===a.nodeType&&1===b.nodeType&&a.sourceIndex-b.sourceIndex;if(d)return d;if(c)for(;c=c.nextSibling;)if(c===b)return-1;return a?1:-1}function l(a){return function(b){return"input"===b.nodeName.toLowerCase()&&b.type===a}}function k(a){return function(b){var c=b.nodeName.toLowerCase();return("input"===c||"button"===c)&&b.type===a}}function m(a){return function(b){return"form"in
b?b.parentNode&&!1===b.disabled?"label"in b?"label"in b.parentNode?b.parentNode.disabled===a:b.disabled===a:b.isDisabled===a||b.isDisabled!==!a&&wa(b)===a:b.disabled===a:"label"in b?b.disabled===a:!1}}function n(a){return c(function(b){b=+b;return c(function(c,d){for(var e,f=a([],c.length,b),g=f.length;g--;)c[e=f[g]]&&(c[e]=!(d[e]=c[e]))})})}function q(a){return a&&"undefined"!==typeof a.getElementsByTagName&&a}function w(){}function p(a){for(var b=0,c=a.length,d="";b<c;b++)d+=a[b].value;return d}
function Ca(a,b,c){var d=b.dir,e=b.next,f=e||d,g=c&&"parentNode"===f,C=E++;return b.first?function(b,c,e){for(;b=b[d];)if(1===b.nodeType||g)return a(b,c,e);return!1}:function(b,c,h){var u,l=[ea,C];if(h)for(;b=b[d];){if((1===b.nodeType||g)&&a(b,c,h))return!0}else for(;b=b[d];)if(1===b.nodeType||g){var k=b[A]||(b[A]={});k=k[b.uniqueID]||(k[b.uniqueID]={});if(e&&e===b.nodeName.toLowerCase())b=b[d]||b;else{if((u=k[f])&&u[0]===ea&&u[1]===C)return l[2]=u[2];k[f]=l;if(l[2]=a(b,c,h))return!0}}return!1}}function v(a){return 1<
a.length?function(b,c,d){for(var e=a.length;e--;)if(!a[e](b,c,d))return!1;return!0}:a[0]}function r(a,b,c,d,e){for(var f,g=[],C=0,h=a.length,u=null!=b;C<h;C++)if(f=a[C])if(!c||c(f,d,e))g.push(f),u&&b.push(C);return g}function t(a,d,e,f,g,h){f&&!f[A]&&(f=t(f));g&&!g[A]&&(g=t(g,h));return c(function(c,C,h,u){var l,k=[],m=[],K=C.length,O;if(!(O=c)){O=d||"*";for(var n=h.nodeType?[h]:h,za=[],Aa=0,q=n.length;Aa<q;Aa++)b(O,n[Aa],za);O=za}O=!a||!c&&d?O:r(O,k,a,h,u);n=e?g||(c?a:K||f)?[]:C:O;e&&e(O,n,h,u);
if(f){var w=r(n,m);f(w,[],h,u);for(h=w.length;h--;)if(l=w[h])n[m[h]]=!(O[m[h]]=l)}if(c){if(g||a){if(g){w=[];for(h=n.length;h--;)(l=n[h])&&w.push(O[h]=l);g(null,n=[],w,u)}for(h=n.length;h--;)(l=n[h])&&-1<(w=g?B(c,l):k[h])&&(c[w]=!(C[w]=l))}}else n=r(n===C?n.splice(K,n.length):n),g?g(null,C,n,u):pa.apply(C,n)})}function y(a){var b,c,d=a.length,e=D.relative[a[0].type];var f=e||D.relative[" "];for(var g=e?1:0,h=Ca(function(a){return a===b},f,!0),C=Ca(function(a){return-1<B(b,a)},f,!0),l=[function(a,c,
d){a=!e&&(d||c!==Q)||((b=c).nodeType?h(a,c,d):C(a,c,d));b=null;return a}];g<d;g++)if(f=D.relative[a[g].type])l=[Ca(v(l),f)];else{f=D.filter[a[g].type].apply(null,a[g].matches);if(f[A]){for(c=++g;c<d&&!D.relative[a[c].type];c++);return t(1<g&&v(l),1<g&&p(a.slice(0,g-1).concat({value:" "===a[g-2].type?"*":""})).replace(T,"$1"),f,g<c&&y(a.slice(g,c)),c<d&&y(a=a.slice(c)),c<d&&p(a))}l.push(f)}return v(l)}function hc(a,d){var e=0<d.length,f=0<a.length,g=function(c,g,h,C,l){var u,k,m=0,K="0",O=c&&[],n=
[],za=Q,q=c||f&&D.find.TAG("*",l),w=ea+=null==za?1:Math.random()||.1,Aa=q.length;for(l&&(Q=g===x||g||l);K!==Aa&&null!=(u=q[K]);K++){if(f&&u){var p=0;g||u.ownerDocument===x||(ua(u),h=!U);for(;k=a[p++];)if(k(u,g||x,h)){C.push(u);break}l&&(ea=w)}e&&((u=!k&&u)&&m--,c&&O.push(u))}m+=K;if(e&&K!==m){for(p=0;k=d[p++];)k(O,n,g,h);if(c){if(0<m)for(;K--;)O[K]||n[K]||(n[K]=S.call(C));n=r(n)}pa.apply(C,n);l&&!c&&0<n.length&&1<m+d.length&&b.uniqueSort(C)}l&&(ea=w,Q=za);return O};return e?c(g):g}var L,Q,J,R,x,V,
U,P,va,Ja,Ba,A="sizzle"+1*new Date,G=a.document,ea=0,E=0,z=d(),H=d(),Ia=d(),M=function(a,b){a===b&&(R=!0);return 0},N={}.hasOwnProperty,F=[],S=F.pop,Y=F.push,pa=F.push,Z=F.slice,B=function(a,b){for(var c=0,d=a.length;c<d;c++)if(a[c]===b)return c;return-1},ca=RegExp("[\\x20\\t\\r\\n\\f]+","g"),T=RegExp("^[\\x20\\t\\r\\n\\f]+|((?:^|[^\\\\])(?:\\\\.)*)[\\x20\\t\\r\\n\\f]+$","g"),da=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,ha=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,ia=RegExp("=[\\x20\\t\\r\\n\\f]*([^\\]'\"]*?)[\\x20\\t\\r\\n\\f]*\\]",
"g"),la=/:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,ma=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,X={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:/^\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\]/,
PSEUDO:/^:((?:\\.|[\w-]|[^\x00-\xa0])+)(?:\((('((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)")|((?:\\.|[^\\()[\]]|\[[\x20\t\r\n\f]*((?:\\.|[\w-]|[^\x00-\xa0])+)(?:[\x20\t\r\n\f]*([*^$|!~]?=)[\x20\t\r\n\f]*(?:'((?:\\.|[^\\'])*)'|"((?:\\.|[^\\"])*)"|((?:\\.|[\w-]|[^\x00-\xa0])+))|)[\x20\t\r\n\f]*\])*)|.*)\)|)/,CHILD:/^:(only|first|last|nth|nth-last)-(child|of-type)(?:\([\x20\t\r\n\f]*(even|odd|(([+-]|)(\d*)n|)[\x20\t\r\n\f]*(?:([+-]|)[\x20\t\r\n\f]*(\d+)|))[\x20\t\r\n\f]*\)|)/i,bool:/^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$/i,
needsContext:/^[\x20\t\r\n\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\([\x20\t\r\n\f]*((?:-\d)?\d*)[\x20\t\r\n\f]*\)|)(?=[^-]|$)/i},oa=/^(?:input|select|textarea|button)$/i,qa=/^h\d$/i,W=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ba=/[+~]/,fa=RegExp("\\\\([\\da-f]{1,6}[\\x20\\t\\r\\n\\f]?|([\\x20\\t\\r\\n\\f])|.)","ig"),ga=function(a,b,c){a="0x"+b-65536;return a!==a||c?b:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)},ka=/([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,
na=function(a,b){return b?"\x00"===a?"\ufffd":a.slice(0,-1)+"\\"+a.charCodeAt(a.length-1).toString(16)+" ":"\\"+a},ra=function(){ua()},wa=Ca(function(a){return!0===a.disabled&&("form"in a||"label"in a)},{dir:"parentNode",next:"legend"});try{pa.apply(F=Z.call(G.childNodes),G.childNodes),F[G.childNodes.length].nodeType}catch(C){pa={apply:F.length?function(a,b){Y.apply(a,Z.call(b))}:function(a,b){for(var c=a.length,d=0;a[c++]=b[d++];);a.length=c-1}}}var I=b.support={};var xa=b.isXML=function(a){return(a=
a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};var ua=b.setDocument=function(a){var b;a=a?a.ownerDocument||a:G;if(a===x||9!==a.nodeType||!a.documentElement)return x;x=a;V=x.documentElement;U=!xa(x);G!==x&&(b=x.defaultView)&&b.top!==b&&(b.addEventListener?b.addEventListener("unload",ra,!1):b.attachEvent&&b.attachEvent("onunload",ra));I.attributes=f(function(a){a.className="i";return!a.getAttribute("className")});I.getElementsByTagName=f(function(a){a.appendChild(x.createComment(""));
return!a.getElementsByTagName("*").length});I.getElementsByClassName=W.test(x.getElementsByClassName);I.getById=f(function(a){V.appendChild(a).id=A;return!x.getElementsByName||!x.getElementsByName(A).length});I.getById?(D.filter.ID=function(a){var b=a.replace(fa,ga);return function(a){return a.getAttribute("id")===b}},D.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&U){var c=b.getElementById(a);return c?[c]:[]}}):(D.filter.ID=function(a){var b=a.replace(fa,ga);return function(a){return(a=
"undefined"!==typeof a.getAttributeNode&&a.getAttributeNode("id"))&&a.value===b}},D.find.ID=function(a,b){if("undefined"!==typeof b.getElementById&&U){var c,d,e=b.getElementById(a);if(e){if((c=e.getAttributeNode("id"))&&c.value===a)return[e];var f=b.getElementsByName(a);for(d=0;e=f[d++];)if((c=e.getAttributeNode("id"))&&c.value===a)return[e]}return[]}});D.find.TAG=I.getElementsByTagName?function(a,b){if("undefined"!==typeof b.getElementsByTagName)return b.getElementsByTagName(a);if(I.qsa)return b.querySelectorAll(a)}:
function(a,b){var c,d=[],e=0,f=b.getElementsByTagName(a);if("*"===a){for(;c=f[e++];)1===c.nodeType&&d.push(c);return d}return f};D.find.CLASS=I.getElementsByClassName&&function(a,b){if("undefined"!==typeof b.getElementsByClassName&&U)return b.getElementsByClassName(a)};va=[];P=[];if(I.qsa=W.test(x.querySelectorAll))f(function(a){V.appendChild(a).innerHTML="<a id='"+A+"'></a><select id='"+A+"-\r\\' msallowcapture=''><option selected=''></option></select>";a.querySelectorAll("[msallowcapture^='']").length&&
P.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||P.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");a.querySelectorAll("[id~="+A+"-]").length||P.push("~=");a.querySelectorAll(":checked").length||P.push(":checked");a.querySelectorAll("a#"+A+"+*").length||P.push(".#.+[+~]")}),f(function(a){a.innerHTML="<a href='' disabled='disabled'></a><select disabled='disabled'><option/></select>";
var b=x.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&P.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");2!==a.querySelectorAll(":enabled").length&&P.push(":enabled",":disabled");V.appendChild(a).disabled=!0;2!==a.querySelectorAll(":disabled").length&&P.push(":enabled",":disabled");a.querySelectorAll("*,:x");P.push(",.*:")});(I.matchesSelector=W.test(Ja=V.matches||V.webkitMatchesSelector||V.mozMatchesSelector||V.oMatchesSelector||
V.msMatchesSelector))&&f(function(a){I.disconnectedMatch=Ja.call(a,"*");Ja.call(a,"[s!='']:x");va.push("!=",":((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});P=P.length&&new RegExp(P.join("|"));
va=va.length&&new RegExp(va.join("|"));Ba=(b=W.test(V.compareDocumentPosition))||W.test(V.contains)?function(a,b){var c=9===a.nodeType?a.documentElement:a,d=b&&b.parentNode;return a===d||!!(d&&1===d.nodeType&&(c.contains?c.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16))}:function(a,b){if(b)for(;b=b.parentNode;)if(b===a)return!0;return!1};M=b?function(a,b){if(a===b)return R=!0,0;var c=!a.compareDocumentPosition-!b.compareDocumentPosition;if(c)return c;c=(a.ownerDocument||a)===
(b.ownerDocument||b)?a.compareDocumentPosition(b):1;return c&1||!I.sortDetached&&b.compareDocumentPosition(a)===c?a===x||a.ownerDocument===G&&Ba(G,a)?-1:b===x||b.ownerDocument===G&&Ba(G,b)?1:J?B(J,a)-B(J,b):0:c&4?-1:1}:function(a,b){if(a===b)return R=!0,0;var c=0;var d=a.parentNode;var e=b.parentNode,f=[a],g=[b];if(!d||!e)return a===x?-1:b===x?1:d?-1:e?1:J?B(J,a)-B(J,b):0;if(d===e)return h(a,b);for(d=a;d=d.parentNode;)f.unshift(d);for(d=b;d=d.parentNode;)g.unshift(d);for(;f[c]===g[c];)c++;return c?
h(f[c],g[c]):f[c]===G?-1:g[c]===G?1:0};return x};b.matches=function(a,c){return b(a,null,null,c)};b.matchesSelector=function(a,c){(a.ownerDocument||a)!==x&&ua(a);c=c.replace(ia,"='$1']");if(!(!I.matchesSelector||!U||Ia[c+" "]||va&&va.test(c)||P&&P.test(c)))try{var d=Ja.call(a,c);if(d||I.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(O){}return 0<b(c,x,null,[a]).length};b.contains=function(a,b){(a.ownerDocument||a)!==x&&ua(a);return Ba(a,b)};b.attr=function(a,b){(a.ownerDocument||
a)!==x&&ua(a);var c=D.attrHandle[b.toLowerCase()],c=c&&N.call(D.attrHandle,b.toLowerCase())?c(a,b,!U):void 0;return void 0!==c?c:I.attributes||!U?a.getAttribute(b):(c=a.getAttributeNode(b))&&c.specified?c.value:null};b.escape=function(a){return(a+"").replace(ka,na)};b.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};b.uniqueSort=function(a){var b,c=[],d=0,e=0;R=!I.detectDuplicates;J=!I.sortStable&&a.slice(0);a.sort(M);if(R){for(;b=a[e++];)b===a[e]&&(d=c.push(e));for(;d--;)a.splice(c[d],
1)}J=null;return a};var ja=b.getText=function(a){var b="",c=0;var d=a.nodeType;if(!d)for(;d=a[c++];)b+=ja(d);else if(1===d||9===d||11===d){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=ja(a)}else if(3===d||4===d)return a.nodeValue;return b};var D=b.selectors={cacheLength:50,createPseudo:c,match:X,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},
preFilter:{ATTR:function(a){a[1]=a[1].replace(fa,ga);a[3]=(a[3]||a[4]||a[5]||"").replace(fa,ga);"~="===a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||b.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&b.error(a[0]);return a},PSEUDO:function(a){var b,c=!a[6]&&a[2];if(X.CHILD.test(a[0]))return null;a[3]?a[2]=a[4]||a[5]||"":c&&la.test(c)&&(b=aa(c,!0))&&(b=c.indexOf(")",
c.length-b)-c.length)&&(a[0]=a[0].slice(0,b),a[2]=c.slice(0,b));return a.slice(0,3)}},filter:{TAG:function(a){var b=a.replace(fa,ga).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===b}},CLASS:function(a){var b=z[a+" "];return b||(b=new RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"),z(a,function(a){return b.test("string"===typeof a.className&&a.className||"undefined"!==typeof a.getAttribute&&a.getAttribute("class")||"")}))},ATTR:function(a,
c,d){return function(e){e=b.attr(e,a);if(null==e)return"!="===c;if(!c)return!0;e+="";return"="===c?e===d:"!="===c?e!==d:"^="===c?d&&0===e.indexOf(d):"*="===c?d&&-1<e.indexOf(d):"$="===c?d&&e.slice(-d.length)===d:"~="===c?-1<(" "+e.replace(ca," ")+" ").indexOf(d):"|="===c?e===d||e.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,b,c,d,e){var f="nth"!==a.slice(0,3),g="last"!==a.slice(-4),h="of-type"===b;return 1===d&&0===e?function(a){return!!a.parentNode}:function(b,c,l){var k,m;c=f!==g?"nextSibling":
"previousSibling";var C=b.parentNode,n=h&&b.nodeName.toLowerCase();l=!l&&!h;var u=!1;if(C){if(f){for(;c;){for(k=b;k=k[c];)if(h?k.nodeName.toLowerCase()===n:1===k.nodeType)return!1;var K=c="only"===a&&!K&&"nextSibling"}return!0}K=[g?C.firstChild:C.lastChild];if(g&&l){k=C;var q=k[A]||(k[A]={});q=q[k.uniqueID]||(q[k.uniqueID]={});u=q[a]||[];u=(m=u[0]===ea&&u[1])&&u[2];for(k=m&&C.childNodes[m];k=++m&&k&&k[c]||(u=m=0)||K.pop();)if(1===k.nodeType&&++u&&k===b){q[a]=[ea,m,u];break}}else if(l&&(k=b,q=k[A]||
(k[A]={}),q=q[k.uniqueID]||(q[k.uniqueID]={}),u=q[a]||[],u=m=u[0]===ea&&u[1]),!1===u)for(;(k=++m&&k&&k[c]||(u=m=0)||K.pop())&&((h?k.nodeName.toLowerCase()!==n:1!==k.nodeType)||!++u||(l&&(q=k[A]||(k[A]={}),q=q[k.uniqueID]||(q[k.uniqueID]={}),q[a]=[ea,u]),k!==b)););u-=e;return u===d||0===u%d&&0<=u/d}}},PSEUDO:function(a,d){var e=D.pseudos[a]||D.setFilters[a.toLowerCase()]||b.error("unsupported pseudo: "+a);if(e[A])return e(d);if(1<e.length){var f=[a,a,"",d];return D.setFilters.hasOwnProperty(a.toLowerCase())?
c(function(a,b){for(var c,f=e(a,d),g=f.length;g--;)c=B(a,f[g]),a[c]=!(b[c]=f[g])}):function(a){return e(a,0,f)}}return e}},pseudos:{not:c(function(a){var b=[],d=[],e=ta(a.replace(T,"$1"));return e[A]?c(function(a,b,c,d){d=e(a,null,d,[]);for(var f=a.length;f--;)if(c=d[f])a[f]=!(b[f]=c)}):function(a,c,f){b[0]=a;e(b,null,f,d);b[0]=null;return!d.pop()}}),has:c(function(a){return function(c){return 0<b(a,c).length}}),contains:c(function(a){a=a.replace(fa,ga);return function(b){return-1<(b.textContent||
b.innerText||ja(b)).indexOf(a)}}),lang:c(function(a){ma.test(a||"")||b.error("unsupported lang: "+a);a=a.replace(fa,ga).toLowerCase();return function(b){var c;do if(c=U?b.lang:b.getAttribute("xml:lang")||b.getAttribute("lang"))return c=c.toLowerCase(),c===a||0===c.indexOf(a+"-");while((b=b.parentNode)&&1===b.nodeType);return!1}}),target:function(b){var c=a.location&&a.location.hash;return c&&c.slice(1)===b.id},root:function(a){return a===V},focus:function(a){return a===x.activeElement&&(!x.hasFocus||
x.hasFocus())&&!!(a.type||a.href||~a.tabIndex)},enabled:m(!1),disabled:m(!0),checked:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&!!a.checked||"option"===b&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!D.pseudos.empty(a)},header:function(a){return qa.test(a.nodeName)},input:function(a){return oa.test(a.nodeName)},
button:function(a){var b=a.nodeName.toLowerCase();return"input"===b&&"button"===a.type||"button"===b},text:function(a){var b;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(b=a.getAttribute("type"))||"text"===b.toLowerCase())},first:n(function(){return[0]}),last:n(function(a,b){return[b-1]}),eq:n(function(a,b,c){return[0>c?c+b:c]}),even:n(function(a,b){for(var c=0;c<b;c+=2)a.push(c);return a}),odd:n(function(a,b){for(var c=1;c<b;c+=2)a.push(c);return a}),lt:n(function(a,b,c){for(b=
0>c?c+b:c;0<=--b;)a.push(b);return a}),gt:n(function(a,b,c){for(c=0>c?c+b:c;++c<b;)a.push(c);return a})}};D.pseudos.nth=D.pseudos.eq;for(L in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})D.pseudos[L]=l(L);for(L in{submit:!0,reset:!0})D.pseudos[L]=k(L);w.prototype=D.filters=D.pseudos;D.setFilters=new w;var aa=b.tokenize=function(a,c){var d,e,f,g,h;if(g=H[a+" "])return c?0:g.slice(0);g=a;var k=[];for(h=D.preFilter;g;){if(!l||(d=da.exec(g)))d&&(g=g.slice(d[0].length)||g),k.push(e=[]);var l=!1;
if(d=ha.exec(g))l=d.shift(),e.push({value:l,type:d[0].replace(T," ")}),g=g.slice(l.length);for(f in D.filter)!(d=X[f].exec(g))||h[f]&&!(d=h[f](d))||(l=d.shift(),e.push({value:l,type:f,matches:d}),g=g.slice(l.length));if(!l)break}return c?g.length:g?b.error(a):H(a,k).slice(0)};var ta=b.compile=function(a,b){var c,d=[],e=[],f=Ia[a+" "];if(!f){b||(b=aa(a));for(c=b.length;c--;)f=y(b[c]),f[A]?d.push(f):e.push(f);f=Ia(a,hc(e,d));f.selector=a}return f};var ya=b.select=function(a,b,c,d){var e,f,g,h="function"===
typeof a&&a,l=!d&&aa(a=h.selector||a);c=c||[];if(1===l.length){var k=l[0]=l[0].slice(0);if(2<k.length&&"ID"===(f=k[0]).type&&9===b.nodeType&&U&&D.relative[k[1].type]){b=(D.find.ID(f.matches[0].replace(fa,ga),b)||[])[0];if(!b)return c;h&&(b=b.parentNode);a=a.slice(k.shift().value.length)}for(e=X.needsContext.test(a)?0:k.length;e--;){f=k[e];if(D.relative[g=f.type])break;if(g=D.find[g])if(d=g(f.matches[0].replace(fa,ga),ba.test(k[0].type)&&q(b.parentNode)||b)){k.splice(e,1);a=d.length&&p(k);if(!a)return pa.apply(c,
d),c;break}}}(h||ta(a,l))(d,b,!U,c,!b||ba.test(a)&&q(b.parentNode)||b);return c};I.sortStable=A.split("").sort(M).join("")===A;I.detectDuplicates=!!R;ua();I.sortDetached=f(function(a){return a.compareDocumentPosition(x.createElement("fieldset"))&1});f(function(a){a.innerHTML="<a href='#'></a>";return"#"===a.firstChild.getAttribute("href")})||g("type|href|height|width",function(a,b,c){if(!c)return a.getAttribute(b,"type"===b.toLowerCase()?1:2)});I.attributes&&f(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value",
"");return""===a.firstChild.getAttribute("value")})||g("value",function(a,b,c){if(!c&&"input"===a.nodeName.toLowerCase())return a.defaultValue});f(function(a){return null==a.getAttribute("disabled")})||g("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",function(a,b,c){var d;if(!c)return!0===a[b]?b.toLowerCase():(d=a.getAttributeNode(b))&&d.specified?d.value:null});return b}(p);c.find=ha;c.expr=ha.selectors;c.expr[":"]=c.expr.pseudos;
c.uniqueSort=c.unique=ha.uniqueSort;c.text=ha.getText;c.isXMLDoc=ha.isXML;c.contains=ha.contains;c.escapeSelector=ha.escape;var qa=function(a,b,d){for(var e=[],f=void 0!==d;(a=a[b])&&9!==a.nodeType;)if(1===a.nodeType){if(f&&c(a).is(d))break;e.push(a)}return e},Bb=function(a,b){for(var c=[];a;a=a.nextSibling)1===a.nodeType&&a!==b&&c.push(a);return c},Cb=c.expr.match.needsContext,Db=/^<([a-z][^\/\0>:\x20\t\r\n\f]*)[\x20\t\r\n\f]*\/?>(?:<\/\1>|)$/i,Qb=/^.[^:#\[\.,]*$/;c.filter=function(a,b,d){var e=
b[0];d&&(a=":not("+a+")");return 1===b.length&&1===e.nodeType?c.find.matchesSelector(e,a)?[e]:[]:c.find.matches(a,c.grep(b,function(a){return 1===a.nodeType}))};c.fn.extend({find:function(a){var b,d=this.length,e=this;if("string"!==typeof a)return this.pushStack(c(a).filter(function(){for(b=0;b<d;b++)if(c.contains(e[b],this))return!0}));var f=this.pushStack([]);for(b=0;b<d;b++)c.find(a,e[b],f);return 1<d?c.uniqueSort(f):f},filter:function(a){return this.pushStack(Na(this,a||[],!1))},not:function(a){return this.pushStack(Na(this,
a||[],!0))},is:function(a){return!!Na(this,"string"===typeof a&&Cb.test(a)?c(a):a||[],!1).length}});var jc=/^(?:\s*(<[\w\W]+>)[^>]*|#([\w-]+))$/;(c.fn.init=function(a,b,d){if(!a)return this;d=d||kc;if("string"===typeof a){var e="<"===a[0]&&">"===a[a.length-1]&&3<=a.length?[null,a,null]:jc.exec(a);if(!e||!e[1]&&b)return!b||b.jquery?(b||d).find(a):this.constructor(b).find(a);if(e[1]){if(b=b instanceof c?b[0]:b,c.merge(this,c.parseHTML(e[1],b&&b.nodeType?b.ownerDocument||b:r,!0)),Db.test(e[1])&&c.isPlainObject(b))for(e in b)if(c.isFunction(this[e]))this[e](b[e]);
else this.attr(e,b[e])}else if(a=r.getElementById(e[2]))this[0]=a,this.length=1;return this}return a.nodeType?(this[0]=a,this.length=1,this):c.isFunction(a)?void 0!==d.ready?d.ready(a):a(c):c.makeArray(a,this)}).prototype=c.fn;var kc=c(r);var lc=/^(?:parents|prev(?:Until|All))/,mc={children:!0,contents:!0,next:!0,prev:!0};c.fn.extend({has:function(a){var b=c(a,this),d=b.length;return this.filter(function(){for(var a=0;a<d;a++)if(c.contains(this,b[a]))return!0})},closest:function(a,b){var d,e=0,f=
this.length,g=[],h="string"!==typeof a&&c(a);if(!Cb.test(a))for(;e<f;e++)for(d=this[e];d&&d!==b;d=d.parentNode)if(11>d.nodeType&&(h?-1<h.index(d):1===d.nodeType&&c.find.matchesSelector(d,a))){g.push(d);break}return this.pushStack(1<g.length?c.uniqueSort(g):g)},index:function(a){return a?"string"===typeof a?sa.call(c(a),this[0]):sa.call(this,a.jquery?a[0]:a):this[0]&&this[0].parentNode?this.first().prevAll().length:-1},add:function(a,b){return this.pushStack(c.uniqueSort(c.merge(this.get(),c(a,b))))},
addBack:function(a){return this.add(null==a?this.prevObject:this.prevObject.filter(a))}});c.each({parent:function(a){return(a=a.parentNode)&&11!==a.nodeType?a:null},parents:function(a){return qa(a,"parentNode")},parentsUntil:function(a,b,c){return qa(a,"parentNode",c)},next:function(a){return ab(a,"nextSibling")},prev:function(a){return ab(a,"previousSibling")},nextAll:function(a){return qa(a,"nextSibling")},prevAll:function(a){return qa(a,"previousSibling")},nextUntil:function(a,b,c){return qa(a,
"nextSibling",c)},prevUntil:function(a,b,c){return qa(a,"previousSibling",c)},siblings:function(a){return Bb((a.parentNode||{}).firstChild,a)},children:function(a){return Bb(a.firstChild)},contents:function(a){if(F(a,"iframe"))return a.contentDocument;F(a,"template")&&(a=a.content||a);return c.merge([],a.childNodes)}},function(a,b){c.fn[a]=function(d,e){var f=c.map(this,b,d);"Until"!==a.slice(-5)&&(e=d);e&&"string"===typeof e&&(f=c.filter(e,f));1<this.length&&(mc[a]||c.uniqueSort(f),lc.test(a)&&f.reverse());
return this.pushStack(f)}});var M=/[^\x20\t\r\n\f]+/g;c.Callbacks=function(a){a="string"===typeof a?Rb(a):c.extend({},a);var b,d,e,f,g=[],h=[],l=-1,k=function(){f=f||a.once;for(e=b=!0;h.length;l=-1)for(d=h.shift();++l<g.length;)!1===g[l].apply(d[0],d[1])&&a.stopOnFalse&&(l=g.length,d=!1);a.memory||(d=!1);b=!1;f&&(g=d?[]:"")},m={add:function(){g&&(d&&!b&&(l=g.length-1,h.push(d)),function q(b){c.each(b,function(b,d){c.isFunction(d)?a.unique&&m.has(d)||g.push(d):d&&d.length&&"string"!==c.type(d)&&q(d)})}(arguments),
d&&!b&&k());return this},remove:function(){c.each(arguments,function(a,b){for(var d;-1<(d=c.inArray(b,g,d));)g.splice(d,1),d<=l&&l--});return this},has:function(a){return a?-1<c.inArray(a,g):0<g.length},empty:function(){g&&(g=[]);return this},disable:function(){f=h=[];g=d="";return this},disabled:function(){return!g},lock:function(){f=h=[];d||b||(g=d="");return this},locked:function(){return!!f},fireWith:function(a,c){f||(c=c||[],c=[a,c.slice?c.slice():c],h.push(c),b||k());return this},fire:function(){m.fireWith(this,
arguments);return this},fired:function(){return!!e}};return m};c.extend({Deferred:function(a){var b=[["notify","progress",c.Callbacks("memory"),c.Callbacks("memory"),2],["resolve","done",c.Callbacks("once memory"),c.Callbacks("once memory"),0,"resolved"],["reject","fail",c.Callbacks("once memory"),c.Callbacks("once memory"),1,"rejected"]],d="pending",e={state:function(){return d},always:function(){f.done(arguments).fail(arguments);return this},"catch":function(a){return e.then(null,a)},pipe:function(){var a=
arguments;return c.Deferred(function(d){c.each(b,function(b,e){var g=c.isFunction(a[e[4]])&&a[e[4]];f[e[1]](function(){var a=g&&g.apply(this,arguments);if(a&&c.isFunction(a.promise))a.promise().progress(d.notify).done(d.resolve).fail(d.reject);else d[e[0]+"With"](this,g?[a]:arguments)})});a=null}).promise()},then:function(a,d,e){function f(a,b,d,e){return function(){var h=this,l=arguments,k=function(){if(!(a<g)){var k=d.apply(h,l);if(k===b.promise())throw new TypeError("Thenable self-resolution");
var m=k&&("object"===typeof k||"function"===typeof k)&&k.then;c.isFunction(m)?e?m.call(k,f(g,b,ia,e),f(g,b,ja,e)):(g++,m.call(k,f(g,b,ia,e),f(g,b,ja,e),f(g,b,ia,b.notifyWith))):(d!==ia&&(h=void 0,l=[k]),(e||b.resolveWith)(h,l))}},m=e?k:function(){try{k()}catch(y){c.Deferred.exceptionHook&&c.Deferred.exceptionHook(y,m.stackTrace),a+1>=g&&(d!==ja&&(h=void 0,l=[y]),b.rejectWith(h,l))}};a?m():(c.Deferred.getStackHook&&(m.stackTrace=c.Deferred.getStackHook()),p.setTimeout(m))}}var g=0;return c.Deferred(function(g){b[0][3].add(f(0,
g,c.isFunction(e)?e:ia,g.notifyWith));b[1][3].add(f(0,g,c.isFunction(a)?a:ia));b[2][3].add(f(0,g,c.isFunction(d)?d:ja))}).promise()},promise:function(a){return null!=a?c.extend(a,e):e}},f={};c.each(b,function(a,c){var g=c[2],h=c[5];e[c[1]]=g.add;h&&g.add(function(){d=h},b[3-a][2].disable,b[0][2].lock);g.add(c[3].fire);f[c[0]]=function(){f[c[0]+"With"](this===f?void 0:this,arguments);return this};f[c[0]+"With"]=g.fireWith});e.promise(f);a&&a.call(f,f);return f},when:function(a){var b=arguments.length,
d=b,e=Array(d),f=da.call(arguments),g=c.Deferred(),h=function(a){return function(c){e[a]=this;f[a]=1<arguments.length?da.call(arguments):c;--b||g.resolveWith(e,f)}};if(1>=b&&(bb(a,g.done(h(d)).resolve,g.reject,!b),"pending"===g.state()||c.isFunction(f[d]&&f[d].then)))return g.then();for(;d--;)bb(f[d],h(d),g.reject);return g.promise()}});var nc=/^(Eval|Internal|Range|Reference|Syntax|Type|URI)Error$/;c.Deferred.exceptionHook=function(a,b){p.console&&p.console.warn&&a&&nc.test(a.name)&&p.console.warn("jQuery.Deferred exception: "+
a.message,a.stack,b)};c.readyException=function(a){p.setTimeout(function(){throw a;})};var Wa=c.Deferred();c.fn.ready=function(a){Wa.then(a)["catch"](function(a){c.readyException(a)});return this};c.extend({isReady:!1,readyWait:1,ready:function(a){(!0===a?--c.readyWait:c.isReady)||(c.isReady=!0,!0!==a&&0<--c.readyWait||Wa.resolveWith(r,[c]))}});c.ready.then=Wa.then;"complete"===r.readyState||"loading"!==r.readyState&&!r.documentElement.doScroll?p.setTimeout(c.ready):(r.addEventListener("DOMContentLoaded",
aa),p.addEventListener("load",aa));var Y=function(a,b,d,e,f,g,h){var l=0,k=a.length,m=null==d;if("object"===c.type(d))for(l in f=!0,d)Y(a,b,l,d[l],!0,g,h);else if(void 0!==e&&(f=!0,c.isFunction(e)||(h=!0),m&&(h?(b.call(a,e),b=null):(m=b,b=function(a,b,d){return m.call(c(a),d)})),b))for(;l<k;l++)b(a[l],d,h?e:e.call(a[l],l,b(a[l],d)));return f?a:m?b.call(a):k?b(a[0],d):g},Ka=function(a){return 1===a.nodeType||9===a.nodeType||!+a.nodeType};ba.uid=1;ba.prototype={cache:function(a){var b=a[this.expando];
b||(b={},Ka(a)&&(a.nodeType?a[this.expando]=b:Object.defineProperty(a,this.expando,{value:b,configurable:!0})));return b},set:function(a,b,d){var e;a=this.cache(a);if("string"===typeof b)a[c.camelCase(b)]=d;else for(e in b)a[c.camelCase(e)]=b[e];return a},get:function(a,b){return void 0===b?this.cache(a):a[this.expando]&&a[this.expando][c.camelCase(b)]},access:function(a,b,c){if(void 0===b||b&&"string"===typeof b&&void 0===c)return this.get(a,b);this.set(a,b,c);return void 0!==c?c:b},remove:function(a,
b){var d,e=a[this.expando];if(void 0!==e){if(void 0!==b)for(Array.isArray(b)?b=b.map(c.camelCase):(b=c.camelCase(b),b=b in e?[b]:b.match(M)||[]),d=b.length;d--;)delete e[b[d]];if(void 0===b||c.isEmptyObject(e))a.nodeType?a[this.expando]=void 0:delete a[this.expando]}},hasData:function(a){a=a[this.expando];return void 0!==a&&!c.isEmptyObject(a)}};var v=new ba,E=new ba,Tb=/^(?:\{[\w\W]*\}|\[[\w\W]*\])$/,Sb=/[A-Z]/g;c.extend({hasData:function(a){return E.hasData(a)||v.hasData(a)},data:function(a,b,c){return E.access(a,
b,c)},removeData:function(a,b){E.remove(a,b)},_data:function(a,b,c){return v.access(a,b,c)},_removeData:function(a,b){v.remove(a,b)}});c.fn.extend({data:function(a,b){var d,e=this[0],f=e&&e.attributes;if(void 0===a){if(this.length){var g=E.get(e);if(1===e.nodeType&&!v.get(e,"hasDataAttrs")){for(d=f.length;d--;)if(f[d]){var h=f[d].name;0===h.indexOf("data-")&&(h=c.camelCase(h.slice(5)),cb(e,h,g[h]))}v.set(e,"hasDataAttrs",!0)}}return g}return"object"===typeof a?this.each(function(){E.set(this,a)}):
Y(this,function(b){if(e&&void 0===b){var c=E.get(e,a);if(void 0!==c)return c;c=cb(e,a);if(void 0!==c)return c}else this.each(function(){E.set(this,a,b)})},null,b,1<arguments.length,null,!0)},removeData:function(a){return this.each(function(){E.remove(this,a)})}});c.extend({queue:function(a,b,d){if(a){b=(b||"fx")+"queue";var e=v.get(a,b);d&&(!e||Array.isArray(d)?e=v.access(a,b,c.makeArray(d)):e.push(d));return e||[]}},dequeue:function(a,b){b=b||"fx";var d=c.queue(a,b),e=d.length,f=d.shift(),g=c._queueHooks(a,
b),h=function(){c.dequeue(a,b)};"inprogress"===f&&(f=d.shift(),e--);f&&("fx"===b&&d.unshift("inprogress"),delete g.stop,f.call(a,h,g));!e&&g&&g.empty.fire()},_queueHooks:function(a,b){var d=b+"queueHooks";return v.get(a,d)||v.access(a,d,{empty:c.Callbacks("once memory").add(function(){v.remove(a,[b+"queue",d])})})}});c.fn.extend({queue:function(a,b){var d=2;"string"!==typeof a&&(b=a,a="fx",d--);return arguments.length<d?c.queue(this[0],a):void 0===b?this:this.each(function(){var d=c.queue(this,a,
b);c._queueHooks(this,a);"fx"===a&&"inprogress"!==d[0]&&c.dequeue(this,a)})},dequeue:function(a){return this.each(function(){c.dequeue(this,a)})},clearQueue:function(a){return this.queue(a||"fx",[])},promise:function(a,b){var d,e=1,f=c.Deferred(),g=this,h=this.length,l=function(){--e||f.resolveWith(g,[g])};"string"!==typeof a&&(b=a,a=void 0);for(a=a||"fx";h--;)(d=v.get(g[h],a+"queueHooks"))&&d.empty&&(e++,d.empty.add(l));l();return f.promise(b)}});var Eb=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,
ka=new RegExp("^(?:([+-])=|)("+Eb+")([a-z%]*)$","i"),Z=["Top","Right","Bottom","Left"],ta=function(a,b){a=b||a;return"none"===a.style.display||""===a.style.display&&c.contains(a.ownerDocument,a)&&"none"===c.css(a,"display")},Fb=function(a,b,c,e){var d,g={};for(d in b)g[d]=a.style[d],a.style[d]=b[d];c=c.apply(a,e||[]);for(d in b)a.style[d]=g[d];return c},eb={};c.fn.extend({show:function(){return la(this,!0)},hide:function(){return la(this)},toggle:function(a){return"boolean"===typeof a?a?this.show():
this.hide():this.each(function(){ta(this)?c(this).show():c(this).hide()})}});var Gb=/^(?:checkbox|radio)$/i,gb=/<([a-z][^\/\0>\x20\t\r\n\f]+)/i,hb=/^$|\/(?:java|ecma)script/i,N={option:[1,"<select multiple='multiple'>","</select>"],thead:[1,"<table>","</table>"],col:[2,"<table><colgroup>","</colgroup></table>"],tr:[2,"<table><tbody>","</tbody></table>"],td:[3,"<table><tbody><tr>","</tr></tbody></table>"],_default:[0,"",""]};N.optgroup=N.option;N.tbody=N.tfoot=N.colgroup=N.caption=N.thead;N.th=N.td;
var Ub=/<|&#?\w+;/;(function(){var a=r.createDocumentFragment().appendChild(r.createElement("div")),b=r.createElement("input");b.setAttribute("type","radio");b.setAttribute("checked","checked");b.setAttribute("name","t");a.appendChild(b);t.checkClone=a.cloneNode(!0).cloneNode(!0).lastChild.checked;a.innerHTML="<textarea>x</textarea>";t.noCloneChecked=!!a.cloneNode(!0).lastChild.defaultValue})();var La=r.documentElement,oc=/^key/,pc=/^(?:mouse|pointer|contextmenu|drag|drop)|click/,Hb=/^([^.]*)(?:\.(.+)|)/;
c.event={global:{},add:function(a,b,d,e,f){var g,h,l,k,m;if(l=v.get(a)){if(d.handler){var n=d;d=n.handler;f=n.selector}f&&c.find.matchesSelector(La,f);d.guid||(d.guid=c.guid++);(h=l.events)||(h=l.events={});(g=l.handle)||(g=l.handle=function(b){return"undefined"!==typeof c&&c.event.triggered!==b.type?c.event.dispatch.apply(a,arguments):void 0});b=(b||"").match(M)||[""];for(l=b.length;l--;){var q=Hb.exec(b[l])||[];var w=k=q[1];var p=(q[2]||"").split(".").sort();w&&(q=c.event.special[w]||{},w=(f?q.delegateType:
q.bindType)||w,q=c.event.special[w]||{},k=c.extend({type:w,origType:k,data:e,handler:d,guid:d.guid,selector:f,needsContext:f&&c.expr.match.needsContext.test(f),namespace:p.join(".")},n),(m=h[w])||(m=h[w]=[],m.delegateCount=0,q.setup&&!1!==q.setup.call(a,e,p,g)||a.addEventListener&&a.addEventListener(w,g)),q.add&&(q.add.call(a,k),k.handler.guid||(k.handler.guid=d.guid)),f?m.splice(m.delegateCount++,0,k):m.push(k),c.event.global[w]=!0)}}},remove:function(a,b,d,e,f){var g,h,l,k,m,n=v.hasData(a)&&v.get(a);
if(n&&(l=n.events)){b=(b||"").match(M)||[""];for(k=b.length;k--;){var q=Hb.exec(b[k])||[];var p=m=q[1];var r=(q[2]||"").split(".").sort();if(p){var t=c.event.special[p]||{};p=(e?t.delegateType:t.bindType)||p;var F=l[p]||[];q=q[2]&&new RegExp("(^|\\.)"+r.join("\\.(?:.*\\.|)")+"(\\.|$)");for(h=g=F.length;g--;){var z=F[g];!f&&m!==z.origType||d&&d.guid!==z.guid||q&&!q.test(z.namespace)||e&&e!==z.selector&&("**"!==e||!z.selector)||(F.splice(g,1),z.selector&&F.delegateCount--,t.remove&&t.remove.call(a,
z))}h&&!F.length&&(t.teardown&&!1!==t.teardown.call(a,r,n.handle)||c.removeEvent(a,p,n.handle),delete l[p])}else for(p in l)c.event.remove(a,p+b[k],d,e,!0)}c.isEmptyObject(l)&&v.remove(a,"handle events")}},dispatch:function(a){var b=c.event.fix(a),d,e,f,g=Array(arguments.length);var h=(v.get(this,"events")||{})[b.type]||[];var l=c.event.special[b.type]||{};g[0]=b;for(d=1;d<arguments.length;d++)g[d]=arguments[d];b.delegateTarget=this;if(!l.preDispatch||!1!==l.preDispatch.call(this,b)){var k=c.event.handlers.call(this,
b,h);for(d=0;(f=k[d++])&&!b.isPropagationStopped();)for(b.currentTarget=f.elem,h=0;(e=f.handlers[h++])&&!b.isImmediatePropagationStopped();)if(!b.rnamespace||b.rnamespace.test(e.namespace))b.handleObj=e,b.data=e.data,e=((c.event.special[e.origType]||{}).handle||e.handler).apply(f.elem,g),void 0!==e&&!1===(b.result=e)&&(b.preventDefault(),b.stopPropagation());l.postDispatch&&l.postDispatch.call(this,b);return b.result}},handlers:function(a,b){var d,e=[],f=b.delegateCount,g=a.target;if(f&&g.nodeType&&
!("click"===a.type&&1<=a.button))for(;g!==this;g=g.parentNode||this)if(1===g.nodeType&&("click"!==a.type||!0!==g.disabled)){var h=[];var l={};for(d=0;d<f;d++){var k=b[d];var m=k.selector+" ";void 0===l[m]&&(l[m]=k.needsContext?-1<c(m,this).index(g):c.find(m,this,null,[g]).length);l[m]&&h.push(k)}h.length&&e.push({elem:g,handlers:h})}f<b.length&&e.push({elem:this,handlers:b.slice(f)});return e},addProp:function(a,b){Object.defineProperty(c.Event.prototype,a,{enumerable:!0,configurable:!0,get:c.isFunction(b)?
function(){if(this.originalEvent)return b(this.originalEvent)}:function(){if(this.originalEvent)return this.originalEvent[a]},set:function(b){Object.defineProperty(this,a,{enumerable:!0,configurable:!0,writable:!0,value:b})}})},fix:function(a){return a[c.expando]?a:new c.Event(a)},special:{load:{noBubble:!0},focus:{trigger:function(){if(this!==ib()&&this.focus)return this.focus(),!1},delegateType:"focusin"},blur:{trigger:function(){if(this===ib()&&this.blur)return this.blur(),!1},delegateType:"focusout"},
click:{trigger:function(){if("checkbox"===this.type&&this.click&&F(this,"input"))return this.click(),!1},_default:function(a){return F(a.target,"a")}},beforeunload:{postDispatch:function(a){void 0!==a.result&&a.originalEvent&&(a.originalEvent.returnValue=a.result)}}}};c.removeEvent=function(a,b,c){a.removeEventListener&&a.removeEventListener(b,c)};c.Event=function(a,b){if(!(this instanceof c.Event))return new c.Event(a,b);a&&a.type?(this.originalEvent=a,this.type=a.type,this.isDefaultPrevented=a.defaultPrevented||
void 0===a.defaultPrevented&&!1===a.returnValue?ya:ma,this.target=a.target&&3===a.target.nodeType?a.target.parentNode:a.target,this.currentTarget=a.currentTarget,this.relatedTarget=a.relatedTarget):this.type=a;b&&c.extend(this,b);this.timeStamp=a&&a.timeStamp||c.now();this[c.expando]=!0};c.Event.prototype={constructor:c.Event,isDefaultPrevented:ma,isPropagationStopped:ma,isImmediatePropagationStopped:ma,isSimulated:!1,preventDefault:function(){var a=this.originalEvent;this.isDefaultPrevented=ya;a&&
!this.isSimulated&&a.preventDefault()},stopPropagation:function(){var a=this.originalEvent;this.isPropagationStopped=ya;a&&!this.isSimulated&&a.stopPropagation()},stopImmediatePropagation:function(){var a=this.originalEvent;this.isImmediatePropagationStopped=ya;a&&!this.isSimulated&&a.stopImmediatePropagation();this.stopPropagation()}};c.each({altKey:!0,bubbles:!0,cancelable:!0,changedTouches:!0,ctrlKey:!0,detail:!0,eventPhase:!0,metaKey:!0,pageX:!0,pageY:!0,shiftKey:!0,view:!0,"char":!0,charCode:!0,
key:!0,keyCode:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pointerId:!0,pointerType:!0,screenX:!0,screenY:!0,targetTouches:!0,toElement:!0,touches:!0,which:function(a){var b=a.button;return null==a.which&&oc.test(a.type)?null!=a.charCode?a.charCode:a.keyCode:!a.which&&void 0!==b&&pc.test(a.type)?b&1?1:b&2?3:b&4?2:0:a.which}},c.event.addProp);c.each({mouseenter:"mouseover",mouseleave:"mouseout",pointerenter:"pointerover",pointerleave:"pointerout"},function(a,b){c.event.special[a]=
{delegateType:b,bindType:b,handle:function(a){var d=a.relatedTarget,f=a.handleObj;if(!d||d!==this&&!c.contains(this,d)){a.type=f.origType;var g=f.handler.apply(this,arguments);a.type=b}return g}}});c.fn.extend({on:function(a,b,c,e){return Pa(this,a,b,c,e)},one:function(a,b,c,e){return Pa(this,a,b,c,e,1)},off:function(a,b,d){if(a&&a.preventDefault&&a.handleObj){var e=a.handleObj;c(a.delegateTarget).off(e.namespace?e.origType+"."+e.namespace:e.origType,e.selector,e.handler);return this}if("object"===
typeof a){for(e in a)this.off(e,b,a[e]);return this}if(!1===b||"function"===typeof b)d=b,b=void 0;!1===d&&(d=ma);return this.each(function(){c.event.remove(this,a,d,b)})}});var qc=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([a-z][^\/\0>\x20\t\r\n\f]*)[^>]*)\/>/gi,rc=/<script|<style|<link/i,Yb=/checked\s*(?:[^=]|=\s*.checked.)/i,Xb=/^true\/(.*)/,Zb=/^\s*<!(?:\[CDATA\[|--)|(?:\]\]|--)>\s*$/g;c.extend({htmlPrefilter:function(a){return a.replace(qc,"<$1></$2>")},clone:function(a,b,d){var e,
f=a.cloneNode(!0),g=c.contains(a.ownerDocument,a);if(!(t.noCloneChecked||1!==a.nodeType&&11!==a.nodeType||c.isXMLDoc(a))){var h=z(f);var l=z(a);var k=0;for(e=l.length;k<e;k++){var m=l[k],n=h[k],q=n.nodeName.toLowerCase();if("input"===q&&Gb.test(m.type))n.checked=m.checked;else if("input"===q||"textarea"===q)n.defaultValue=m.defaultValue}}if(b)if(d)for(l=l||z(a),h=h||z(f),k=0,e=l.length;k<e;k++)kb(l[k],h[k]);else kb(a,f);h=z(f,"script");0<h.length&&Oa(h,!g&&z(a,"script"));return f},cleanData:function(a){for(var b,
d,e,f=c.event.special,g=0;void 0!==(d=a[g]);g++)if(Ka(d)){if(b=d[v.expando]){if(b.events)for(e in b.events)f[e]?c.event.remove(d,e):c.removeEvent(d,e,b.handle);d[v.expando]=void 0}d[E.expando]&&(d[E.expando]=void 0)}}});c.fn.extend({detach:function(a){return mb(this,a,!0)},remove:function(a){return mb(this,a)},text:function(a){return Y(this,function(a){return void 0===a?c.text(this):this.empty().each(function(){if(1===this.nodeType||11===this.nodeType||9===this.nodeType)this.textContent=a})},null,
a,arguments.length)},append:function(){return X(this,arguments,function(a){1!==this.nodeType&&11!==this.nodeType&&9!==this.nodeType||jb(this,a).appendChild(a)})},prepend:function(){return X(this,arguments,function(a){if(1===this.nodeType||11===this.nodeType||9===this.nodeType){var b=jb(this,a);b.insertBefore(a,b.firstChild)}})},before:function(){return X(this,arguments,function(a){this.parentNode&&this.parentNode.insertBefore(a,this)})},after:function(){return X(this,arguments,function(a){this.parentNode&&
this.parentNode.insertBefore(a,this.nextSibling)})},empty:function(){for(var a,b=0;null!=(a=this[b]);b++)1===a.nodeType&&(c.cleanData(z(a,!1)),a.textContent="");return this},clone:function(a,b){a=null==a?!1:a;b=null==b?a:b;return this.map(function(){return c.clone(this,a,b)})},html:function(a){return Y(this,function(a){var b=this[0]||{},e=0,f=this.length;if(void 0===a&&1===b.nodeType)return b.innerHTML;if("string"===typeof a&&!rc.test(a)&&!N[(gb.exec(a)||["",""])[1].toLowerCase()]){a=c.htmlPrefilter(a);
try{for(;e<f;e++)b=this[e]||{},1===b.nodeType&&(c.cleanData(z(b,!1)),b.innerHTML=a);b=0}catch(g){}}b&&this.empty().append(a)},null,a,arguments.length)},replaceWith:function(){var a=[];return X(this,arguments,function(b){var d=this.parentNode;0>c.inArray(this,a)&&(c.cleanData(z(this)),d&&d.replaceChild(b,this))},a)}});c.each({appendTo:"append",prependTo:"prepend",insertBefore:"before",insertAfter:"after",replaceAll:"replaceWith"},function(a,b){c.fn[a]=function(a){for(var d=[],f=c(a),g=f.length-1,h=
0;h<=g;h++)a=h===g?this:this.clone(!0),c(f[h])[b](a),Va.apply(d,a.get());return this.pushStack(d)}});var nb=/^margin/,Qa=new RegExp("^("+Eb+")(?!px)[a-z%]+$","i"),Da=function(a){var b=a.ownerDocument.defaultView;b&&b.opener||(b=p);return b.getComputedStyle(a)};(function(){function a(){if(h){h.style.cssText="box-sizing:border-box;position:relative;display:block;margin:auto;border:1px;padding:1px;top:1%;width:50%";h.innerHTML="";La.appendChild(g);var a=p.getComputedStyle(h);b="1%"!==a.top;f="2px"===
a.marginLeft;d="4px"===a.width;h.style.marginRight="50%";e="4px"===a.marginRight;La.removeChild(g);h=null}}var b,d,e,f,g=r.createElement("div"),h=r.createElement("div");h.style&&(h.style.backgroundClip="content-box",h.cloneNode(!0).style.backgroundClip="",t.clearCloneStyle="content-box"===h.style.backgroundClip,g.style.cssText="border:0;width:8px;height:0;top:0;left:-9999px;padding:0;margin-top:1px;position:absolute",g.appendChild(h),c.extend(t,{pixelPosition:function(){a();return b},boxSizingReliable:function(){a();
return d},pixelMarginRight:function(){a();return e},reliableMarginLeft:function(){a();return f}}))})();var sc=/^(none|table(?!-c[ea]).+)/,Ib=/^--/,tc={position:"absolute",visibility:"hidden",display:"block"},Jb={letterSpacing:"0",fontWeight:"400"},rb=["Webkit","Moz","ms"],qb=r.createElement("div").style;c.extend({cssHooks:{opacity:{get:function(a,b){if(b){var c=na(a,"opacity");return""===c?"1":c}}}},cssNumber:{animationIterationCount:!0,columnCount:!0,fillOpacity:!0,flexGrow:!0,flexShrink:!0,fontWeight:!0,
lineHeight:!0,opacity:!0,order:!0,orphans:!0,widows:!0,zIndex:!0,zoom:!0},cssProps:{"float":"cssFloat"},style:function(a,b,d,e){if(a&&3!==a.nodeType&&8!==a.nodeType&&a.style){var f,g=c.camelCase(b),h=Ib.test(b),l=a.style;h||(b=pb(g));var k=c.cssHooks[b]||c.cssHooks[g];if(void 0!==d){var m=typeof d;"string"===m&&(f=ka.exec(d))&&f[1]&&(d=db(a,b,f),m="number");null!=d&&d===d&&("number"===m&&(d+=f&&f[3]||(c.cssNumber[g]?"":"px")),t.clearCloneStyle||""!==d||0!==b.indexOf("background")||(l[b]="inherit"),
k&&"set"in k&&void 0===(d=k.set(a,d,e))||(h?l.setProperty(b,d):l[b]=d))}else return k&&"get"in k&&void 0!==(f=k.get(a,!1,e))?f:l[b]}},css:function(a,b,d,e){var f;var g=c.camelCase(b);Ib.test(b)||(b=pb(g));(g=c.cssHooks[b]||c.cssHooks[g])&&"get"in g&&(f=g.get(a,!0,d));void 0===f&&(f=na(a,b,e));"normal"===f&&b in Jb&&(f=Jb[b]);return""===d||d?(a=parseFloat(f),!0===d||isFinite(a)?a||0:f):f}});c.each(["height","width"],function(a,b){c.cssHooks[b]={get:function(a,e,f){if(e)return!sc.test(c.css(a,"display"))||
a.getClientRects().length&&a.getBoundingClientRect().width?ub(a,b,f):Fb(a,tc,function(){return ub(a,b,f)})},set:function(a,e,f){var d,h=f&&Da(a);(f=f&&tb(a,b,f,"border-box"===c.css(a,"boxSizing",!1,h),h))&&(d=ka.exec(e))&&"px"!==(d[3]||"px")&&(a.style[b]=e,e=c.css(a,b));return sb(a,e,f)}}});c.cssHooks.marginLeft=ob(t.reliableMarginLeft,function(a,b){if(b)return(parseFloat(na(a,"marginLeft"))||a.getBoundingClientRect().left-Fb(a,{marginLeft:0},function(){return a.getBoundingClientRect().left}))+"px"});
c.each({margin:"",padding:"",border:"Width"},function(a,b){c.cssHooks[a+b]={expand:function(c){var d=0,f={};for(c="string"===typeof c?c.split(" "):[c];4>d;d++)f[a+Z[d]+b]=c[d]||c[d-2]||c[0];return f}};nb.test(a)||(c.cssHooks[a+b].set=sb)});c.fn.extend({css:function(a,b){return Y(this,function(a,b,f){var d,e={},l=0;if(Array.isArray(b)){f=Da(a);for(d=b.length;l<d;l++)e[b[l]]=c.css(a,b[l],!1,f);return e}return void 0!==f?c.style(a,b,f):c.css(a,b)},a,b,1<arguments.length)}});c.Tween=H;H.prototype={constructor:H,
init:function(a,b,d,e,f,g){this.elem=a;this.prop=d;this.easing=f||c.easing._default;this.options=b;this.start=this.now=this.cur();this.end=e;this.unit=g||(c.cssNumber[d]?"":"px")},cur:function(){var a=H.propHooks[this.prop];return a&&a.get?a.get(this):H.propHooks._default.get(this)},run:function(a){var b,d=H.propHooks[this.prop];this.pos=this.options.duration?b=c.easing[this.easing](a,this.options.duration*a,0,1,this.options.duration):b=a;this.now=(this.end-this.start)*b+this.start;this.options.step&&
this.options.step.call(this.elem,this.now,this);d&&d.set?d.set(this):H.propHooks._default.set(this);return this}};H.prototype.init.prototype=H.prototype;H.propHooks={_default:{get:function(a){return 1!==a.elem.nodeType||null!=a.elem[a.prop]&&null==a.elem.style[a.prop]?a.elem[a.prop]:(a=c.css(a.elem,a.prop,""))&&"auto"!==a?a:0},set:function(a){if(c.fx.step[a.prop])c.fx.step[a.prop](a);else 1!==a.elem.nodeType||null==a.elem.style[c.cssProps[a.prop]]&&!c.cssHooks[a.prop]?a.elem[a.prop]=a.now:c.style(a.elem,
a.prop,a.now+a.unit)}}};H.propHooks.scrollTop=H.propHooks.scrollLeft={set:function(a){a.elem.nodeType&&a.elem.parentNode&&(a.elem[a.prop]=a.now)}};c.easing={linear:function(a){return a},swing:function(a){return.5-Math.cos(a*Math.PI)/2},_default:"swing"};c.fx=H.prototype.init;c.fx.step={};var oa,Ea,uc=/^(?:toggle|show|hide)$/,vc=/queueHooks$/;c.Animation=c.extend(S,{tweeners:{"*":[function(a,b){var c=this.createTween(a,b);db(c.elem,a,ka.exec(b),c);return c}]},tweener:function(a,b){c.isFunction(a)?
(b=a,a=["*"]):a=a.match(M);for(var d,e=0,f=a.length;e<f;e++)d=a[e],S.tweeners[d]=S.tweeners[d]||[],S.tweeners[d].unshift(b)},prefilters:[function(a,b,d){var e;var f="width"in b||"height"in b;var g=this,h={},l=a.style,k=a.nodeType&&ta(a),m=v.get(a,"fxshow");if(!d.queue){var n=c._queueHooks(a,"fx");if(null==n.unqueued){n.unqueued=0;var q=n.empty.fire;n.empty.fire=function(){n.unqueued||q()}}n.unqueued++;g.always(function(){g.always(function(){n.unqueued--;c.queue(a,"fx").length||n.empty.fire()})})}for(e in b){var p=
b[e];if(uc.test(p)){delete b[e];var r=r||"toggle"===p;if(p===(k?"hide":"show"))if("show"===p&&m&&void 0!==m[e])k=!0;else continue;h[e]=m&&m[e]||c.style(a,e)}}if((b=!c.isEmptyObject(b))||!c.isEmptyObject(h)){if(f&&1===a.nodeType){d.overflow=[l.overflow,l.overflowX,l.overflowY];var t=m&&m.display;null==t&&(t=v.get(a,"display"));f=c.css(a,"display");"none"===f&&(t?f=t:(la([a],!0),t=a.style.display||t,f=c.css(a,"display"),la([a])));("inline"===f||"inline-block"===f&&null!=t)&&"none"===c.css(a,"float")&&
(b||(g.done(function(){l.display=t}),null==t&&(f=l.display,t="none"===f?"":f)),l.display="inline-block")}d.overflow&&(l.overflow="hidden",g.always(function(){l.overflow=d.overflow[0];l.overflowX=d.overflow[1];l.overflowY=d.overflow[2]}));b=!1;for(e in h)b||(m?"hidden"in m&&(k=m.hidden):m=v.access(a,"fxshow",{display:t}),r&&(m.hidden=!k),k&&la([a],!0),g.done(function(){k||la([a]);v.remove(a,"fxshow");for(e in h)c.style(a,e,h[e])})),b=wb(k?m[e]:0,e,g),e in m||(m[e]=b.start,k&&(b.end=b.start,b.start=
0))}}],prefilter:function(a,b){b?S.prefilters.unshift(a):S.prefilters.push(a)}});c.speed=function(a,b,d){var e=a&&"object"===typeof a?c.extend({},a):{complete:d||!d&&b||c.isFunction(a)&&a,duration:a,easing:d&&b||b&&!c.isFunction(b)&&b};c.fx.off?e.duration=0:"number"!==typeof e.duration&&(e.duration=e.duration in c.fx.speeds?c.fx.speeds[e.duration]:c.fx.speeds._default);if(null==e.queue||!0===e.queue)e.queue="fx";e.old=e.complete;e.complete=function(){c.isFunction(e.old)&&e.old.call(this);e.queue&&
c.dequeue(this,e.queue)};return e};c.fn.extend({fadeTo:function(a,b,c,e){return this.filter(ta).css("opacity",0).show().end().animate({opacity:b},a,c,e)},animate:function(a,b,d,e){var f=c.isEmptyObject(a),g=c.speed(b,d,e);b=function(){var b=S(this,c.extend({},a),g);(f||v.get(this,"finish"))&&b.stop(!0)};b.finish=b;return f||!1===g.queue?this.each(b):this.queue(g.queue,b)},stop:function(a,b,d){var e=function(a){var b=a.stop;delete a.stop;b(d)};"string"!==typeof a&&(d=b,b=a,a=void 0);b&&!1!==a&&this.queue(a||
"fx",[]);return this.each(function(){var b=!0,g=null!=a&&a+"queueHooks",h=c.timers,l=v.get(this);if(g)l[g]&&l[g].stop&&e(l[g]);else for(g in l)l[g]&&l[g].stop&&vc.test(g)&&e(l[g]);for(g=h.length;g--;)h[g].elem!==this||null!=a&&h[g].queue!==a||(h[g].anim.stop(d),b=!1,h.splice(g,1));!b&&d||c.dequeue(this,a)})},finish:function(a){!1!==a&&(a=a||"fx");return this.each(function(){var b=v.get(this),d=b[a+"queue"];var e=b[a+"queueHooks"];var f=c.timers,g=d?d.length:0;b.finish=!0;c.queue(this,a,[]);e&&e.stop&&
e.stop.call(this,!0);for(e=f.length;e--;)f[e].elem===this&&f[e].queue===a&&(f[e].anim.stop(!0),f.splice(e,1));for(e=0;e<g;e++)d[e]&&d[e].finish&&d[e].finish.call(this);delete b.finish})}});c.each(["toggle","show","hide"],function(a,b){var d=c.fn[b];c.fn[b]=function(a,c,g){return null==a||"boolean"===typeof a?d.apply(this,arguments):this.animate(Fa(b,!0),a,c,g)}});c.each({slideDown:Fa("show"),slideUp:Fa("hide"),slideToggle:Fa("toggle"),fadeIn:{opacity:"show"},fadeOut:{opacity:"hide"},fadeToggle:{opacity:"toggle"}},
function(a,b){c.fn[a]=function(a,c,f){return this.animate(b,a,c,f)}});c.timers=[];c.fx.tick=function(){var a=0,b=c.timers;for(oa=c.now();a<b.length;a++){var d=b[a];d()||b[a]!==d||b.splice(a--,1)}b.length||c.fx.stop();oa=void 0};c.fx.timer=function(a){c.timers.push(a);c.fx.start()};c.fx.interval=13;c.fx.start=function(){Ea||(Ea=!0,Ra())};c.fx.stop=function(){Ea=null};c.fx.speeds={slow:600,fast:200,_default:400};c.fn.delay=function(a,b){a=c.fx?c.fx.speeds[a]||a:a;return this.queue(b||"fx",function(b,
c){var d=p.setTimeout(b,a);c.stop=function(){p.clearTimeout(d)}})};(function(){var a=r.createElement("input"),b=r.createElement("select").appendChild(r.createElement("option"));a.type="checkbox";t.checkOn=""!==a.value;t.optSelected=b.selected;a=r.createElement("input");a.value="t";a.type="radio";t.radioValue="t"===a.value})();var ra=c.expr.attrHandle;c.fn.extend({attr:function(a,b){return Y(this,c.attr,a,b,1<arguments.length)},removeAttr:function(a){return this.each(function(){c.removeAttr(this,a)})}});
c.extend({attr:function(a,b,d){var e,f,g=a.nodeType;if(3!==g&&8!==g&&2!==g){if("undefined"===typeof a.getAttribute)return c.prop(a,b,d);1===g&&c.isXMLDoc(a)||(f=c.attrHooks[b.toLowerCase()]||(c.expr.match.bool.test(b)?wc:void 0));if(void 0!==d){if(null===d){c.removeAttr(a,b);return}if(f&&"set"in f&&void 0!==(e=f.set(a,d,b)))return e;a.setAttribute(b,d+"");return d}if(f&&"get"in f&&null!==(e=f.get(a,b)))return e;e=c.find.attr(a,b);return null==e?void 0:e}},attrHooks:{type:{set:function(a,b){if(!t.radioValue&&
"radio"===b&&F(a,"input")){var c=a.value;a.setAttribute("type",b);c&&(a.value=c);return b}}}},removeAttr:function(a,b){var c,e=0,f=b&&b.match(M);if(f&&1===a.nodeType)for(;c=f[e++];)a.removeAttribute(c)}});var wc={set:function(a,b,d){!1===b?c.removeAttr(a,d):a.setAttribute(d,d);return d}};c.each(c.expr.match.bool.source.match(/\w+/g),function(a,b){var d=ra[b]||c.find.attr;ra[b]=function(a,b,c){var e=b.toLowerCase();if(!c){var f=ra[e];ra[e]=g;var g=null!=d(a,b,c)?e:null;ra[e]=f}return g}});var xc=/^(?:input|select|textarea|button)$/i,
yc=/^(?:a|area)$/i;c.fn.extend({prop:function(a,b){return Y(this,c.prop,a,b,1<arguments.length)},removeProp:function(a){return this.each(function(){delete this[c.propFix[a]||a]})}});c.extend({prop:function(a,b,d){var e,f=a.nodeType;if(3!==f&&8!==f&&2!==f){if(1!==f||!c.isXMLDoc(a)){b=c.propFix[b]||b;var g=c.propHooks[b]}return void 0!==d?g&&"set"in g&&void 0!==(e=g.set(a,d,b))?e:a[b]=d:g&&"get"in g&&null!==(e=g.get(a,b))?e:a[b]}},propHooks:{tabIndex:{get:function(a){var b=c.find.attr(a,"tabindex");
return b?parseInt(b,10):xc.test(a.nodeName)||yc.test(a.nodeName)&&a.href?0:-1}}},propFix:{"for":"htmlFor","class":"className"}});t.optSelected||(c.propHooks.selected={get:function(a){(a=a.parentNode)&&a.parentNode&&a.parentNode.selectedIndex;return null},set:function(a){if(a=a.parentNode)a.selectedIndex,a.parentNode&&a.parentNode.selectedIndex}});c.each("tabIndex readOnly maxLength cellSpacing cellPadding rowSpan colSpan useMap frameBorder contentEditable".split(" "),function(){c.propFix[this.toLowerCase()]=
this});c.fn.extend({addClass:function(a){var b,d,e,f,g,h=0;if(c.isFunction(a))return this.each(function(b){c(this).addClass(a.call(this,b,ca(this)))});if("string"===typeof a&&a)for(b=a.match(M)||[];d=this[h++];){var l=ca(d);if(e=1===d.nodeType&&" "+B(l)+" "){for(g=0;f=b[g++];)0>e.indexOf(" "+f+" ")&&(e+=f+" ");e=B(e);l!==e&&d.setAttribute("class",e)}}return this},removeClass:function(a){var b,d,e,f,g,h=0;if(c.isFunction(a))return this.each(function(b){c(this).removeClass(a.call(this,b,ca(this)))});
if(!arguments.length)return this.attr("class","");if("string"===typeof a&&a)for(b=a.match(M)||[];d=this[h++];){var l=ca(d);if(e=1===d.nodeType&&" "+B(l)+" "){for(g=0;f=b[g++];)for(;-1<e.indexOf(" "+f+" ");)e=e.replace(" "+f+" "," ");e=B(e);l!==e&&d.setAttribute("class",e)}}return this},toggleClass:function(a,b){var d=typeof a;return"boolean"===typeof b&&"string"===d?b?this.addClass(a):this.removeClass(a):c.isFunction(a)?this.each(function(d){c(this).toggleClass(a.call(this,d,ca(this),b),b)}):this.each(function(){var b,
f;if("string"===d){var g=0;var h=c(this);for(f=a.match(M)||[];b=f[g++];)h.hasClass(b)?h.removeClass(b):h.addClass(b)}else if(void 0===a||"boolean"===d)(b=ca(this))&&v.set(this,"__className__",b),this.setAttribute&&this.setAttribute("class",b||!1===a?"":v.get(this,"__className__")||"")})},hasClass:function(a){var b,c=0;for(a=" "+a+" ";b=this[c++];)if(1===b.nodeType&&-1<(" "+B(ca(b))+" ").indexOf(a))return!0;return!1}});var zc=/\r/g;c.fn.extend({val:function(a){var b,d,e=this[0];if(arguments.length){var f=
c.isFunction(a);return this.each(function(d){1===this.nodeType&&(d=f?a.call(this,d,c(this).val()):a,null==d?d="":"number"===typeof d?d+="":Array.isArray(d)&&(d=c.map(d,function(a){return null==a?"":a+""})),b=c.valHooks[this.type]||c.valHooks[this.nodeName.toLowerCase()],b&&"set"in b&&void 0!==b.set(this,d,"value")||(this.value=d))})}if(e){if((b=c.valHooks[e.type]||c.valHooks[e.nodeName.toLowerCase()])&&"get"in b&&void 0!==(d=b.get(e,"value")))return d;d=e.value;return"string"===typeof d?d.replace(zc,
""):null==d?"":d}}});c.extend({valHooks:{option:{get:function(a){var b=c.find.attr(a,"value");return null!=b?b:B(c.text(a))}},select:{get:function(a){var b=a.options,d=a.selectedIndex,e="select-one"===a.type,f=e?null:[],g=e?d+1:b.length;for(a=0>d?g:e?d:0;a<g;a++){var h=b[a];if(!(!h.selected&&a!==d||h.disabled||h.parentNode.disabled&&F(h.parentNode,"optgroup"))){h=c(h).val();if(e)return h;f.push(h)}}return f},set:function(a,b){for(var d,e,f=a.options,g=c.makeArray(b),h=f.length;h--;)if(e=f[h],e.selected=
-1<c.inArray(c.valHooks.option.get(e),g))d=!0;d||(a.selectedIndex=-1);return g}}}});c.each(["radio","checkbox"],function(){c.valHooks[this]={set:function(a,b){if(Array.isArray(b))return a.checked=-1<c.inArray(c(a).val(),b)}};t.checkOn||(c.valHooks[this].get=function(a){return null===a.getAttribute("value")?"on":a.value})});var Kb=/^(?:focusinfocus|focusoutblur)$/;c.extend(c.event,{trigger:function(a,b,d,e){var f,g,h=[d||r],l=Ha.call(a,"type")?a.type:a;var k=Ha.call(a,"namespace")?a.namespace.split("."):
[];var m=f=d=d||r;if(3!==d.nodeType&&8!==d.nodeType&&!Kb.test(l+c.event.triggered)){-1<l.indexOf(".")&&(k=l.split("."),l=k.shift(),k.sort());var n=0>l.indexOf(":")&&"on"+l;a=a[c.expando]?a:new c.Event(l,"object"===typeof a&&a);a.isTrigger=e?2:3;a.namespace=k.join(".");a.rnamespace=a.namespace?new RegExp("(^|\\.)"+k.join("\\.(?:.*\\.|)")+"(\\.|$)"):null;a.result=void 0;a.target||(a.target=d);b=null==b?[a]:c.makeArray(b,[a]);k=c.event.special[l]||{};if(e||!k.trigger||!1!==k.trigger.apply(d,b)){if(!e&&
!k.noBubble&&!c.isWindow(d)){var q=k.delegateType||l;Kb.test(q+l)||(m=m.parentNode);for(;m;m=m.parentNode)h.push(m),f=m;f===(d.ownerDocument||r)&&h.push(f.defaultView||f.parentWindow||p)}for(f=0;(m=h[f++])&&!a.isPropagationStopped();)a.type=1<f?q:k.bindType||l,(g=(v.get(m,"events")||{})[a.type]&&v.get(m,"handle"))&&g.apply(m,b),(g=n&&m[n])&&g.apply&&Ka(m)&&(a.result=g.apply(m,b),!1===a.result&&a.preventDefault());a.type=l;e||a.isDefaultPrevented()||k._default&&!1!==k._default.apply(h.pop(),b)||!Ka(d)||
!n||!c.isFunction(d[l])||c.isWindow(d)||((f=d[n])&&(d[n]=null),c.event.triggered=l,d[l](),c.event.triggered=void 0,f&&(d[n]=f));return a.result}}},simulate:function(a,b,d){a=c.extend(new c.Event,d,{type:a,isSimulated:!0});c.event.trigger(a,null,b)}});c.fn.extend({trigger:function(a,b){return this.each(function(){c.event.trigger(a,b,this)})},triggerHandler:function(a,b){var d=this[0];if(d)return c.event.trigger(a,b,d,!0)}});c.each("blur focus focusin focusout resize scroll click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select submit keydown keypress keyup contextmenu".split(" "),
function(a,b){c.fn[b]=function(a,c){return 0<arguments.length?this.on(b,null,a,c):this.trigger(b)}});c.fn.extend({hover:function(a,b){return this.mouseenter(a).mouseleave(b||a)}});t.focusin="onfocusin"in p;t.focusin||c.each({focus:"focusin",blur:"focusout"},function(a,b){var d=function(a){c.event.simulate(b,a.target,c.event.fix(a))};c.event.special[b]={setup:function(){var c=this.ownerDocument||this,f=v.access(c,b);f||c.addEventListener(a,d,!0);v.access(c,b,(f||0)+1)},teardown:function(){var c=this.ownerDocument||
this,f=v.access(c,b)-1;f?v.access(c,b,f):(c.removeEventListener(a,d,!0),v.remove(c,b))}}});var wa=p.location,Lb=c.now(),Xa=/\?/;c.parseXML=function(a){if(!a||"string"!==typeof a)return null;try{var b=(new p.DOMParser).parseFromString(a,"text/xml")}catch(d){b=void 0}b&&!b.getElementsByTagName("parsererror").length||c.error("Invalid XML: "+a);return b};var ac=/\[\]$/,Mb=/\r?\n/g,Ac=/^(?:submit|button|image|reset|file)$/i,Bc=/^(?:input|select|textarea|keygen)/i;c.param=function(a,b){var d,e=[],f=function(a,
b){var d=c.isFunction(b)?b():b;e[e.length]=encodeURIComponent(a)+"="+encodeURIComponent(null==d?"":d)};if(Array.isArray(a)||a.jquery&&!c.isPlainObject(a))c.each(a,function(){f(this.name,this.value)});else for(d in a)Sa(d,a[d],b,f);return e.join("&")};c.fn.extend({serialize:function(){return c.param(this.serializeArray())},serializeArray:function(){return this.map(function(){var a=c.prop(this,"elements");return a?c.makeArray(a):this}).filter(function(){var a=this.type;return this.name&&!c(this).is(":disabled")&&
!c(this).hasClass("escludeFromSubmit")&&Bc.test(this.nodeName)&&!Ac.test(a)&&(this.checked||!Gb.test(a))}).map(function(a,b){var d=c(this).val();return null==d?null:Array.isArray(d)?c.map(d,function(a){return{name:b.name,value:a.replace(Mb,"\r\n")}}):{name:b.name,value:d.replace(Mb,"\r\n")}}).get()}});var Cc=/%20/g,Dc=/#.*$/,Ec=/([?&])_=[^&]*/,Fc=/^(.*?):[ \t]*([^\r\n]*)$/mg,Gc=/^(?:GET|HEAD)$/,Hc=/^\/\//,Nb={},Ta={},Ob="*/".concat("*"),Ya=r.createElement("a");Ya.href=wa.href;c.extend({active:0,lastModified:{},
etag:{},ajaxSettings:{url:wa.href,type:"GET",isLocal:/^(?:about|app|app-storage|.+-extension|file|res|widget):$/.test(wa.protocol),global:!0,processData:!0,async:!0,contentType:"application/x-www-form-urlencoded; charset=UTF-8",accepts:{"*":Ob,text:"text/plain",html:"text/html",xml:"application/xml, text/xml",json:"application/json, text/javascript"},contents:{xml:/\bxml\b/,html:/\bhtml/,json:/\bjson\b/},responseFields:{xml:"responseXML",text:"responseText",json:"responseJSON"},converters:{"* text":String,
"text html":!0,"text json":JSON.parse,"text xml":c.parseXML},flatOptions:{url:!0,context:!0}},ajaxSetup:function(a,b){return b?Ua(Ua(a,c.ajaxSettings),b):Ua(c.ajaxSettings,a)},ajaxPrefilter:xb(Nb),ajaxTransport:xb(Ta),ajax:function(a,b){function d(a,b,d,g){var k=b;if(!Q){Q=!0;h&&p.clearTimeout(h);e=void 0;f=g||"";y.readyState=0<a?4:0;g=200<=a&&300>a||304===a;if(d){var r=m;for(var w=y,x,J,A,G,z=r.contents,B=r.dataTypes;"*"===B[0];)B.shift(),void 0===x&&(x=r.mimeType||w.getResponseHeader("Content-Type"));
if(x)for(J in z)if(z[J]&&z[J].test(x)){B.unshift(J);break}if(B[0]in d)A=B[0];else{for(J in d){if(!B[0]||r.converters[J+" "+B[0]]){A=J;break}G||(G=J)}A=A||G}A?(A!==B[0]&&B.unshift(A),r=d[A]):r=void 0}a:{d=m;x=r;J=y;A=g;var H,w={},z=d.dataTypes.slice();if(z[1])for(E in d.converters)w[E.toLowerCase()]=d.converters[E];for(G=z.shift();G;){d.responseFields[G]&&(J[d.responseFields[G]]=x);!R&&A&&d.dataFilter&&(x=d.dataFilter(x,d.dataType));var R=G;if(G=z.shift())if("*"===G)G=R;else if("*"!==R&&R!==G){var E=
w[R+" "+G]||w["* "+G];if(!E)for(H in w)if(r=H.split(" "),r[1]===G&&(E=w[R+" "+r[0]]||w["* "+r[0]])){!0===E?E=w[H]:!0!==w[H]&&(G=r[0],z.unshift(r[1]));break}if(!0!==E)if(E&&d["throws"])x=E(x);else try{x=E(x)}catch(ic){r={state:"parsererror",error:E?ic:"No conversion from "+R+" to "+G};break a}}}r={state:"success",data:x}}if(g)if(m.ifModified&&((k=y.getResponseHeader("Last-Modified"))&&(c.lastModified[L]=k),(k=y.getResponseHeader("etag"))&&(c.etag[L]=k)),204===a||"HEAD"===m.type)k="nocontent";else if(304===
a)k="notmodified";else{k=r.state;var M=r.data;var N=r.error;g=!N}else if(N=k,a||!k)k="error",0>a&&(a=0);y.status=a;y.statusText=(b||k)+"";g?t.resolveWith(n,[M,k,y]):t.rejectWith(n,[y,k,N]);y.statusCode(F);F=void 0;l&&q.trigger(g?"ajaxSuccess":"ajaxError",[y,m,g?M:N]);v.fireWith(n,[y,k]);l&&(q.trigger("ajaxComplete",[y,m]),--c.active||c.event.trigger("ajaxStop"))}}"object"===typeof a&&(b=a,a=void 0);b=b||{};var e,f,g,h,l,k,m=c.ajaxSetup({},b),n=m.context||m,q=m.context&&(n.nodeType||n.jquery)?c(n):
c.event,t=c.Deferred(),v=c.Callbacks("once memory"),F=m.statusCode||{},z={},H={},E="canceled",y={readyState:0,getResponseHeader:function(a){var b;if(Q){if(!g)for(g={};b=Fc.exec(f);)g[b[1].toLowerCase()]=b[2];b=g[a.toLowerCase()]}return null==b?null:b},getAllResponseHeaders:function(){return Q?f:null},setRequestHeader:function(a,b){null==Q&&(a=H[a.toLowerCase()]=H[a.toLowerCase()]||a,z[a]=b);return this},overrideMimeType:function(a){null==Q&&(m.mimeType=a);return this},statusCode:function(a){var b;
if(a)if(Q)y.always(a[y.status]);else for(b in a)F[b]=[F[b],a[b]];return this},abort:function(a){a=a||E;e&&e.abort(a);d(0,a);return this}};t.promise(y);m.url=((a||m.url||wa.href)+"").replace(Hc,wa.protocol+"//");m.type=b.method||b.type||m.method||m.type;m.dataTypes=(m.dataType||"*").toLowerCase().match(M)||[""];if(null==m.crossDomain){var B=r.createElement("a");try{B.href=m.url,B.href=B.href,m.crossDomain=Ya.protocol+"//"+Ya.host!==B.protocol+"//"+B.host}catch(J){m.crossDomain=!0}}m.data&&m.processData&&
"string"!==typeof m.data&&(m.data=c.param(m.data,m.traditional));yb(Nb,m,b,y);if(Q)return y;(l=c.event&&m.global)&&0===c.active++&&c.event.trigger("ajaxStart");m.type=m.type.toUpperCase();m.hasContent=!Gc.test(m.type);var L=m.url.replace(Dc,"");m.hasContent?m.data&&m.processData&&0===(m.contentType||"").indexOf("application/x-www-form-urlencoded")&&(m.data=m.data.replace(Cc,"+")):(B=m.url.slice(L.length),m.data&&(L+=(Xa.test(L)?"&":"?")+m.data,delete m.data),!1===m.cache&&(L=L.replace(Ec,"$1"),B=
(Xa.test(L)?"&":"?")+"_="+Lb++ +B),m.url=L+B);m.ifModified&&(c.lastModified[L]&&y.setRequestHeader("If-Modified-Since",c.lastModified[L]),c.etag[L]&&y.setRequestHeader("If-None-Match",c.etag[L]));(m.data&&m.hasContent&&!1!==m.contentType||b.contentType)&&y.setRequestHeader("Content-Type",m.contentType);y.setRequestHeader("Accept",m.dataTypes[0]&&m.accepts[m.dataTypes[0]]?m.accepts[m.dataTypes[0]]+("*"!==m.dataTypes[0]?", "+Ob+"; q=0.01":""):m.accepts["*"]);for(k in m.headers)y.setRequestHeader(k,
m.headers[k]);if(m.beforeSend&&(!1===m.beforeSend.call(n,y,m)||Q))return y.abort();E="abort";v.add(m.complete);y.done(m.success);y.fail(m.error);if(e=yb(Ta,m,b,y)){y.readyState=1;l&&q.trigger("ajaxSend",[y,m]);if(Q)return y;m.async&&0<m.timeout&&(h=p.setTimeout(function(){y.abort("timeout")},m.timeout));try{var Q=!1;e.send(z,d)}catch(J){if(Q)throw J;d(-1,J)}}else d(-1,"No Transport");return y},getJSON:function(a,b,d){return c.get(a,b,d,"json")},getScript:function(a,b){return c.get(a,void 0,b,"script")}});
c.each(["get","post"],function(a,b){c[b]=function(a,e,f,g){c.isFunction(e)&&(g=g||f,f=e,e=void 0);return c.ajax(c.extend({url:a,type:b,dataType:g,data:e,success:f},c.isPlainObject(a)&&a))}});c._evalUrl=function(a){return c.ajax({url:a,type:"GET",dataType:"script",cache:!0,async:!1,global:!1,"throws":!0})};c.fn.extend({wrapAll:function(a){this[0]&&(c.isFunction(a)&&(a=a.call(this[0])),a=c(a,this[0].ownerDocument).eq(0).clone(!0),this[0].parentNode&&a.insertBefore(this[0]),a.map(function(){for(var a=
this;a.firstElementChild;)a=a.firstElementChild;return a}).append(this));return this},wrapInner:function(a){return c.isFunction(a)?this.each(function(b){c(this).wrapInner(a.call(this,b))}):this.each(function(){var b=c(this),d=b.contents();d.length?d.wrapAll(a):b.append(a)})},wrap:function(a){var b=c.isFunction(a);return this.each(function(d){c(this).wrapAll(b?a.call(this,d):a)})},unwrap:function(a){this.parent(a).not("body").each(function(){c(this).replaceWith(this.childNodes)});return this}});c.expr.pseudos.hidden=
function(a){return!c.expr.pseudos.visible(a)};c.expr.pseudos.visible=function(a){return!!(a.offsetWidth||a.offsetHeight||a.getClientRects().length)};c.ajaxSettings.xhr=function(){try{return new p.XMLHttpRequest}catch(a){}};var Ic={0:200,1223:204},xa=c.ajaxSettings.xhr();t.cors=!!xa&&"withCredentials"in xa;t.ajax=xa=!!xa;c.ajaxTransport(function(a){var b,c;if(t.cors||xa&&!a.crossDomain)return{send:function(d,f){var e,h=a.xhr();h.open(a.type,a.url,a.async,a.username,a.password);if(a.xhrFields)for(e in a.xhrFields)h[e]=
a.xhrFields[e];a.mimeType&&h.overrideMimeType&&h.overrideMimeType(a.mimeType);a.crossDomain||d["X-Requested-With"]||(d["X-Requested-With"]="XMLHttpRequest");for(e in d)h.setRequestHeader(e,d[e]);b=function(a){return function(){b&&(b=c=h.onload=h.onerror=h.onabort=h.onreadystatechange=null,"abort"===a?h.abort():"error"===a?"number"!==typeof h.status?f(0,"error"):f(h.status,h.statusText):f(Ic[h.status]||h.status,h.statusText,"text"!==(h.responseType||"text")||"string"!==typeof h.responseText?{binary:h.response}:
{text:h.responseText},h.getAllResponseHeaders()))}};h.onload=b();c=h.onerror=b("error");void 0!==h.onabort?h.onabort=c:h.onreadystatechange=function(){4===h.readyState&&p.setTimeout(function(){b&&c()})};b=b("abort");try{h.send(a.hasContent&&a.data||null)}catch(l){if(b)throw l;}},abort:function(){b&&b()}}});c.ajaxPrefilter(function(a){a.crossDomain&&(a.contents.script=!1)});c.ajaxSetup({accepts:{script:"text/javascript, application/javascript, application/ecmascript, application/x-ecmascript"},contents:{script:/\b(?:java|ecma)script\b/},
converters:{"text script":function(a){c.globalEval(a);return a}}});c.ajaxPrefilter("script",function(a){void 0===a.cache&&(a.cache=!1);a.crossDomain&&(a.type="GET")});c.ajaxTransport("script",function(a){if(a.crossDomain){var b,d;return{send:function(e,f){b=c("<script>").prop({charset:a.scriptCharset,src:a.url}).on("load error",d=function(a){b.remove();d=null;a&&f("error"===a.type?404:200,a.type)});r.head.appendChild(b[0])},abort:function(){d&&d()}}}});var Pb=[],Za=/(=)\?(?=&|$)|\?\?/;c.ajaxSetup({jsonp:"callback",
jsonpCallback:function(){var a=Pb.pop()||c.expando+"_"+Lb++;this[a]=!0;return a}});c.ajaxPrefilter("json jsonp",function(a,b,d){var e,f=!1!==a.jsonp&&(Za.test(a.url)?"url":"string"===typeof a.data&&0===(a.contentType||"").indexOf("application/x-www-form-urlencoded")&&Za.test(a.data)&&"data");if(f||"jsonp"===a.dataTypes[0]){var g=a.jsonpCallback=c.isFunction(a.jsonpCallback)?a.jsonpCallback():a.jsonpCallback;f?a[f]=a[f].replace(Za,"$1"+g):!1!==a.jsonp&&(a.url+=(Xa.test(a.url)?"&":"?")+a.jsonp+"="+
g);a.converters["script json"]=function(){e||c.error(g+" was not called");return e[0]};a.dataTypes[0]="json";var h=p[g];p[g]=function(){e=arguments};d.always(function(){void 0===h?c(p).removeProp(g):p[g]=h;a[g]&&(a.jsonpCallback=b.jsonpCallback,Pb.push(g));e&&c.isFunction(h)&&h(e[0]);e=h=void 0});return"script"}});t.createHTMLDocument=function(){var a=r.implementation.createHTMLDocument("").body;a.innerHTML="<form></form><form></form>";return 2===a.childNodes.length}();c.parseHTML=function(a,b,d){if("string"!==
typeof a)return[];"boolean"===typeof b&&(d=b,b=!1);if(!b)if(t.createHTMLDocument){b=r.implementation.createHTMLDocument("");var e=b.createElement("base");e.href=r.location.href;b.head.appendChild(e)}else b=r;e=Db.exec(a);d=!d&&[];if(e)return[b.createElement(e[1])];e=fb([a],b,d);d&&d.length&&c(d).remove();return c.merge([],e.childNodes)};c.fn.load=function(a,b,d){var e,f,g=this,h=a.indexOf(" ");if(-1<h){var l=B(a.slice(h));a=a.slice(0,h)}c.isFunction(b)?(d=b,b=void 0):b&&"object"===typeof b&&(e="POST");
0<g.length&&c.ajax({url:a,type:e||"GET",dataType:"html",data:b}).done(function(a){f=arguments;g.html(l?c("<div>").append(c.parseHTML(a)).find(l):a)}).always(d&&function(a,b){g.each(function(){d.apply(this,f||[a.responseText,b,a])})});return this};c.each("ajaxStart ajaxStop ajaxComplete ajaxError ajaxSuccess ajaxSend".split(" "),function(a,b){c.fn[b]=function(a){return this.on(b,a)}});c.expr.pseudos.animated=function(a){return c.grep(c.timers,function(b){return a===b.elem}).length};c.offset={setOffset:function(a,
b,d){var e=c.css(a,"position"),f=c(a),g={};"static"===e&&(a.style.position="relative");var h=f.offset();var l=c.css(a,"top");var k=c.css(a,"left");("absolute"===e||"fixed"===e)&&-1<(l+k).indexOf("auto")?(k=f.position(),l=k.top,k=k.left):(l=parseFloat(l)||0,k=parseFloat(k)||0);c.isFunction(b)&&(b=b.call(a,d,c.extend({},h)));null!=b.top&&(g.top=b.top-h.top+l);null!=b.left&&(g.left=b.left-h.left+k);"using"in b?b.using.call(a,g):f.css(g)}};c.fn.extend({offset:function(a){if(arguments.length)return void 0===
a?this:this.each(function(b){c.offset.setOffset(this,a,b)});var b;if(b=this[0]){if(!b.getClientRects().length)return{top:0,left:0};var d=b.getBoundingClientRect();var e=b.ownerDocument;b=e.documentElement;e=e.defaultView;return{top:d.top+e.pageYOffset-b.clientTop,left:d.left+e.pageXOffset-b.clientLeft}}},position:function(){if(this[0]){var a=this[0],b={top:0,left:0};if("fixed"===c.css(a,"position"))var d=a.getBoundingClientRect();else{var e=this.offsetParent();d=this.offset();F(e[0],"html")||(b=e.offset());
b={top:b.top+c.css(e[0],"borderTopWidth",!0),left:b.left+c.css(e[0],"borderLeftWidth",!0)}}return{top:d.top-b.top-c.css(a,"marginTop",!0),left:d.left-b.left-c.css(a,"marginLeft",!0)}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent;a&&"static"===c.css(a,"position");)a=a.offsetParent;return a||La})}});c.each({scrollLeft:"pageXOffset",scrollTop:"pageYOffset"},function(a,b){var d="pageYOffset"===b;c.fn[a]=function(e){return Y(this,function(a,e,h){if(c.isWindow(a))var f=
a;else 9===a.nodeType&&(f=a.defaultView);if(void 0===h)return f?f[b]:a[e];f?f.scrollTo(d?f.pageXOffset:h,d?h:f.pageYOffset):a[e]=h},a,e,arguments.length)}});c.each(["top","left"],function(a,b){c.cssHooks[b]=ob(t.pixelPosition,function(a,e){if(e)return e=na(a,b),Qa.test(e)?c(a).position()[b]+"px":e})});c.each({Height:"height",Width:"width"},function(a,b){c.each({padding:"inner"+a,content:b,"":"outer"+a},function(d,e){c.fn[e]=function(f,g){var h=arguments.length&&(d||"boolean"!==typeof f),l=d||(!0===
f||!0===g?"margin":"border");return Y(this,function(b,d,f){return c.isWindow(b)?0===e.indexOf("outer")?b["inner"+a]:b.document.documentElement["client"+a]:9===b.nodeType?(d=b.documentElement,Math.max(b.body["scroll"+a],d["scroll"+a],b.body["offset"+a],d["offset"+a],d["client"+a])):void 0===f?c.css(b,d,l):c.style(b,d,f,l)},b,h?f:void 0,h)}})});c.fn.extend({bind:function(a,b,c){return this.on(a,null,b,c)},unbind:function(a,b){return this.off(a,null,b)},delegate:function(a,b,c,e){return this.on(b,a,
c,e)},undelegate:function(a,b,c){return 1===arguments.length?this.off(a,"**"):this.off(b,a||"**",c)}});c.holdReady=function(a){a?c.readyWait++:c.ready(!0)};c.isArray=Array.isArray;c.parseJSON=JSON.parse;c.nodeName=F;"function"===typeof define&&define.amd&&define("jquery",[],function(){return c});var Jc=p.jQuery,Kc=p.$;c.noConflict=function(a){p.$===c&&(p.$=Kc);a&&p.jQuery===c&&(p.jQuery=Jc);return c};W||(p.jQuery=p.$=c);return c});