var msBeautify=msBeautify||{};
(function(b){function R(e,d){d=b.extend(!0,{byJson:{data:null,selectedIndex:0,name:null,size:0,multiple:!1,width:250},mainCSS:"dd",height:120,visibleRows:7,rowHeight:0,showIcon:!0,zIndex:9999,useSprite:!1,animStyle:"slideDown",event:"click",openDirection:"auto",jsonTitle:!0,style:"",disabledOpacity:.7,disabledOptionEvents:!0,childWidth:0,enableCheckbox:!1,checkboxNameSuffix:"_mscheck",append:"",prepend:"",reverseMode:!0,roundedCorner:!0,enableAutoFilter:!0,on:{create:null,open:null,close:null,add:null,
remove:null,change:null,blur:null,click:null,dblclick:null,mousemove:null,mouseover:null,mouseout:null,focus:null,mousedown:null,mouseup:null}},d);var l=this,H={postElementHolder:"_msddHolder",postID:"_msdd",postTitleID:"_title",postTitleTextID:"_titleText",postChildID:"_child"},R=d.mainCSS,r=!1,v=!1,n=!1,S={},I={},J=!1,A=!1,y=!1,K=null,F=!1,L,Z=document,M=window.navigator.userAgent,oa=M.match(/msie/i);d.reverseMode=d.reverseMode.toString();d.roundedCorner=d.roundedCorner.toString();var $=function(a){return"[object Array]"==
Object.prototype.toString.call(a)?!0:!1},h=function(a){void 0===S[a]&&(S[a]=Z.getElementById(a));return S[a]},x=function(a){var c=m("postChildID");return b("#"+c+" li._msddli_").index(a)},pa=function(){if(d.byJson.data){var a=["description","image","title"];try{e.id||(e.id="dropdown"+msBeautify.counter);d.byJson.data=eval(d.byJson.data);var c="msdropdown"+msBeautify.counter++,f={};f.id=c;f.name=d.byJson.name||e.id;0<d.byJson.size&&(f.size=d.byJson.size);f.multiple=d.byJson.multiple;for(var g=p("select",
f),c=0;c<d.byJson.data.length;c++){var k=d.byJson.data[c],m=new Option(k.text,k.value),l;for(l in k)if("text"!=l.toLowerCase()){var n=-1!=b.inArray(l.toLowerCase(),a)?"data-":"";m.setAttribute(n+l,k[l])}g.options[c]=m}h(e.id).appendChild(g);g.selectedIndex=d.byJson.selectedIndex;b(g).css({width:d.byJson.width+"px"});e=g}catch(q){throw"There is an error in json data.";}}},m=function(a){return e+H[a]},aa=function(a){return void 0===a.style?"":a.style.cssText},B=function(a){var c="",f="",g="",e=-1,h=
"",m="",l="",q;if(void 0!==a){e=a.title||"";if(""!=e){if((h=/^\{.*\}$/.test(e))&&d.jsonTitle)var n=eval("["+e+"]");f=h&&d.jsonTitle?n[0].title:f;g=h&&d.jsonTitle?n[0].description:g;c=h&&d.jsonTitle?n[0].image:e;l=h&&d.jsonTitle?n[0].imagecss:l}h=a.text||"";e=a.value||"";m=a.className||"";f=b(a).prop("data-title")||b(a).data("title")||f||"";g=b(a).prop("data-description")||b(a).data("description")||g||"";c=b(a).prop("data-image")||b(a).data("image")||c||"";l=b(a).prop("data-imagecss")||b(a).data("imagecss")||
l||"";q=b(a).index()}return{image:c,title:f,description:g,value:e,text:h,className:m,imagecss:l,index:q}},p=function(a,b,f){a=Z.createElement(a);if(b)for(var g in b)switch(g){case "style":a.style.cssText=b[g];break;default:a[g]=b[g]}f&&(a.innerHTML=f);return a},T=function(a){var b={},f=aa(a);0<f.length&&(b.style=f);f=a.disabled?"disabled":"enabled";f=a.selected?f+" selected":f;"yes"==a.attributes["data-selectedcountry"].value&&(f+=" selected");
f+=" _msddli_";b.className=f;0!=d.useSprite&&(b.className=f+" "+a.className);b=p("li",b);f=B(a);""!=f.title&&(b.title=f.title);var g=f.image;if(""!=g&&d.showIcon){var k=p("img");k.src=g;""!=f.imagecss&&(k.className=f.imagecss+" ")}if(""!=f.description)var h=p("span",{className:"description"},f.description);f=p("span",{className:"ddlabel"},a.text||"");!0===d.enableCheckbox&&(g=p("input",{type:"checkbox",name:e+d.checkboxNameSuffix+"[]",value:a.value||"",className:"checkbox"}),b.appendChild(g),!0===
d.enableCheckbox&&(g.checked=a.selected?!0:!1));k&&b.appendChild(k);b.appendChild(f);h?b.appendChild(h):k&&(k.className+="fnone");a=p("div",{className:"clear"});b.appendChild(a);return b},u=function(a){var c=m("postChildID");if(a)return-1==a?b("#"+c).css({height:"auto",overflow:"auto"}):b("#"+c).css("height",a+"px"),!1;var f;a=h(e).options.length;if(a>d.visibleRows||d.visibleRows){f=b("#"+c+" li:first");var g=parseInt(f.css("padding-bottom"))+parseInt(f.css("padding-top"));0===d.rowHeight&&(b("#"+
c).css({visibility:"hidden",display:"block"}),d.rowHeight=Math.ceil(f.height()),b("#"+c).css({visibility:"visible"}),r&&!0!==d.enableCheckbox||b("#"+c).css({display:"none"}));f=(d.rowHeight+g)*Math.min(d.visibleRows,a)+3}else r&&(f=b("#"+e).height());return f},ba=function(){var a=m("postChildID");b("#"+a).on("click",function(a){if(!0===n)return!1;a.preventDefault();a.stopPropagation();r&&U()});b("#"+a+" li.enabled").on("click",function(a){"input"!==a.target.nodeName.toLowerCase()&&C(this)});b("#"+
a+" li.enabled").on("mousedown",function(c){if(!0===n)return!1;L=b("#"+a+" li.selected");K=this;c.preventDefault();c.stopPropagation();!0===d.enableCheckbox&&"input"===c.target.nodeName.toLowerCase()&&(y=!0);if(!0===r)if(v)if(!0===A){b(this).addClass("selected");var f=b("#"+a+" li.selected"),g=x(this);if(1<f.length){c=b("#"+a+" li._msddli_");var e=x(f[0]),f=x(f[1]);g>f&&(e=g,f+=1);for(g=Math.min(e,f);g<=Math.max(e,f);g++){var h=c[g];b(h).hasClass("enabled")&&b(h).addClass("selected")}}}else!0===y?
(b(this).toggleClass("selected"),!0===d.enableCheckbox&&(c=this.childNodes[0],c.checked=!c.checked)):(b("#"+a+" li.selected").removeClass("selected"),b("#"+a+" input:checkbox").prop("checked",!1),b(this).addClass("selected"),!0===d.enableCheckbox&&(this.childNodes[0].checked=!0));else b("#"+a+" li.selected").removeClass("selected"),b(this).addClass("selected");else b("#"+a+" li.selected").removeClass("selected"),b(this).addClass("selected")});b("#"+a+" li.enabled").on("mouseenter",function(a){if(!0===
n)return!1;a.preventDefault();a.stopPropagation();null!=K&&v&&(b(this).addClass("selected"),!0===d.enableCheckbox&&(this.childNodes[0].checked=!0))});b("#"+a+" li.enabled").on("mouseover",function(a){if(!0===n)return!1;b(this).addClass("hover")});b("#"+a+" li.enabled").on("mouseout",function(c){if(!0===n)return!1;b("#"+a+" li.hover").removeClass("hover")});b("#"+a+" li.enabled").on("mouseup",function(c){if(!0===n)return!1;c.preventDefault();c.stopPropagation();!0===d.enableCheckbox&&(y=!1);c=b("#"+
a+" li.selected").length;F=L.length!=c||0==c?!0:!1;N();O();U();K=null});0==d.disabledOptionEvents&&(b("#"+a+" li._msddli_").on("click",function(a){if(!0===n)return!1;D(this,"click")}),b("#"+a+" li._msddli_").on("mouseenter",function(a){if(!0===n)return!1;D(this,"mouseenter")}),b("#"+a+" li._msddli_").on("mouseover",function(a){if(!0===n)return!1;D(this,"mouseover")}),b("#"+a+" li._msddli_").on("mouseout",function(a){if(!0===n)return!1;D(this,"mouseout")}),b("#"+a+" li._msddli_").on("mousedown",function(a){if(!0===
n)return!1;D(this,"mousedown")}),b("#"+a+" li._msddli_").on("mouseup",function(a){if(!0===n)return!1;D(this,"mouseup")}))},ca=function(a,c,f){b("#"+a).off(c,f);b("#"+a).trigger(c);b("#"+a).on(c,f)},wa=function(){var a=m("postID"),c=m("postTitleTextID");m("postChildID");b("#"+a).on(d.event,function(a){if(!0===n)return!1;s(d.event);a.preventDefault();a.stopPropagation();V(a)});b("#"+a).on("keydown",function(a){var b=a.which;!J&&(13==b||38==b||40==b||37==b||39==b||47<=b&&!r)&&(V(a),47<=b?da():(a.preventDefault(),
a.stopImmediatePropagation()))});b("#"+a).on("focus",ea);b("#"+a).on("blur",fa);b("#"+c).on("blur",function(b){ca(a,"focus",ea)});ba();b("#"+a).on("dblclick",qa);b("#"+a).on("mousemove",ra);b("#"+a).on("mouseenter",sa);b("#"+a).on("mouseleave",ta);b("#"+a).on("mousedown",ua);b("#"+a).on("mouseup",va)},ea=function(a){s("focus")},fa=function(a){s("blur")},W=function(){var a=m("postID"),c=m("postChildID");!0===r&&!1===d.enableCheckbox?(b("#"+a+" .ddTitle").hide(),b("#"+c).css({display:"block",position:"relative"})):
(!1===d.enableCheckbox&&(v=!1),b("#"+a+" .ddTitle").show(),b("#"+c).css({display:"none",position:"absolute"}),a=b("#"+c+" li.selected")[0],b("#"+c+" li.selected").removeClass("selected"),c=x(b(a).addClass("selected")),w(c));u(u())},ga=function(){var a=m("postID");!0===n?b("#"+a).addClass("disabledAll"):b("#"+a).removeClass("disabledAll")},ya=function(){var a;a={className:R+" ddcommon"+("true"==d.roundedCorner?" borderRadius":"")};var c=aa(h(e)),f=b("#"+e).outerWidth();a.style="width: "+f+"px;";0<
c.length&&(a.style=a.style+""+c);a.id=m("postID");a.tabIndex=h(e).tabIndex;a=p("div",a);var g;g=0<=h(e).selectedIndex?h(e).options[h(e).selectedIndex]:{value:"",text:""};var k=c="";if(f=b("#"+e).data("usesprite"))d.useSprite=f;0!=d.useSprite&&(c=" "+d.useSprite,k=" "+g.className);var c=p("div",{className:"ddTitle"+c+("true"==d.roundedCorner?" borderRadiusTp":"")}),f=p("span",{className:"divider"}),n=p("span",{className:"ddArrow arrowoff"}),t=m("postTitleID"),k=p("span",{className:"ddTitleText"+k,
id:t});g=B(g);var t=g.image,G=g.text||"";if(""!=t&&d.showIcon){var q=p("img");q.src=t;""!=g.imagecss&&(q.className=g.imagecss+" ")}t=p("span",{className:"ddlabel"},G);c.appendChild(f);c.appendChild(n);q&&k.appendChild(q);k.appendChild(t);c.appendChild(k);q=p("span",{className:"description"},g.description);k.appendChild(q);a.appendChild(c);q=m("postTitleTextID");q=p("input",{id:q,type:"text",value:"",autocomplete:"off",className:"text shadow "+("true"==d.roundedCorner?"borderRadius":""),style:"display: none"});
a.appendChild(q);q={className:"ddChild ddchild_ border shadow",id:m("postChildID")};q.style=0==r?"z-index: "+d.zIndex:"z-index:1";if(c=b("#"+e).data("childwidth")||d.childWidth)q.style=(q.style||"")+";width:"+c;q=p("div",q);c=p("ul");0!=d.useSprite&&(c.className=d.useSprite);f=h(e).children;for(n=0;n<f.length;n++){g=f[n];if("optgroup"==g.nodeName.toLowerCase()){k=p("li",{className:"optgroup"});t=p("span",{className:"optgroupTitle"},g.label);k.appendChild(t);g=g.children;t=p("ul");for(G=0;G<g.length;G++){var s=
T(g[G]);t.appendChild(s)}k.appendChild(t)}else k=T(g);c.appendChild(k)}q.appendChild(c);a.appendChild(q);b("#"+e).after(a);a=m("postElementHolder");0==b("#"+a).length?(q={style:"height: 0px;overflow: hidden;position: absolute;",className:"ddOutOfVision"},q.id=a,q=p("div",q),b("#"+e).after(q),b("#"+e).appendTo(b("#"+a))):b("#"+a).css({height:0,overflow:"hidden",position:"absolute"});h(e).tabIndex=-1;a=m("postTitleTextID");if("true"==d.enableAutoFilter)b("#"+a).on("keyup",xa);W();ga();wa();a=m("postChildID");
""!=d.append&&b("#"+a).append(d.append);""!=d.prepend&&b("#"+a).prepend(d.prepend);"function"==typeof d.on.create&&d.on.create.apply(l,arguments)},ha=function(a){function c(a){b(b("#"+f+" li._msddli_")[a]).addClass("selected");!0===d.enableCheckbox&&b(b("#"+f+" li._msddli_")[a]).find("input.checkbox").prop("checked","checked")}var f=m("postChildID");b("#"+f+" li._msddli_").removeClass("selected");!0===d.enableCheckbox&&b("#"+f+" li._msddli_ input.checkbox").prop("checked",!1);if(!0===$(a))for(var g=
0;g<a.length;g++)c(a[g]);else c(a)},ia=function(a,c){for(var f=m("postChildID"),f=a||b("#"+f+" li.selected"),d=0;d<f.length;d++){var k=!0===c?f[d]:x(f[d]);h(e).options[k].selected="selected"}w(f)},N=function(){var a=m("postChildID"),c=b("#"+a+" li.selected");if(v&&(A||y)||F)h(e).selectedIndex=-1;var f;0==c.length?f=-1:1<c.length?ia(c):f=x(b("#"+a+" li.selected"));(h(e).selectedIndex!=f||F)&&1>=c.length&&(F=!1,P("change"),h(e).selectedIndex=f,w(f),"function"==typeof d.on.change&&(a=z(),d.on.change(a.data,
a.ui)),b("#"+e).trigger("change"))},w=function(a,c){if(void 0!==a){var f,d,k;-1==a?(f=-1,k=d="",E(-1)):"object"!=typeof a?(d=h(e).options[a],f=h(e).selectedIndex=a,d=B(d),k=0<=a?h(e).options[a].text:"",E(void 0,d),d=d.value):(f=c&&c.index||h(e).selectedIndex,d=c&&c.value||h(e).value,k=c&&c.text||h(e).options[h(e).selectedIndex].text||"",E(f));l.selectedIndex=f;l.value=d;l.selectedText=k;f=h(e).children;l.children=f;f=z();l.uiData=f;f=b("#"+e+" option:selected");l.selectedOptions=f}},P=function(a){var c=
{byElement:!1,byJQuery:!1,hasEvent:!1},f=b("#"+e);try{null!==f.prop("on"+a)&&(c.hasEvent=!0,c.byElement=!0)}catch(d){}(f="function"==typeof b._data?b._data(f[0],"events"):f.data("events"))&&f[a]&&(c.hasEvent=!0,c.byJQuery=!0);return c},U=function(){O();b("body").on("click",C);b(document).on("keydown",ja);b(document).on("keyup",ka)},O=function(){b("body").off("click",C);b(document).off("keydown",ja);b(document).off("keyup",ka)},xa=function(a){if(47>a.keyCode&&8!=a.keyCode&&46!=a.keyCode)return!1;a=
m("postChildID");var c=m("postTitleTextID"),c=h(c).value;if(0==c.length)b("#"+a+" li:hidden").show(),u(u());else if(b("#"+a+" li").hide(),c=b("#"+a+" li:Contains('"+c+"')").show(),b("#"+a+" li:visible").length<=d.visibleRows&&u(-1),0<c.length&&!r||!v)b("#"+a+" .selected").removeClass("selected"),b(c[0]).addClass("selected");r||Q()},da=function(){if("true"==d.enableAutoFilter){var a=m("postID"),c=m("postTitleTextID");0<b("#"+c+":hidden").length&&0==y&&(b("#"+c+":hidden").show().val(""),ca(a,"blur",
fa),h(c).focus())}},ja=function(a){m("postTitleTextID");var c=m("postChildID");switch(a.keyCode){case 40:case 39:a.preventDefault();a.stopPropagation();za();break;case 38:case 37:a.preventDefault();a.stopPropagation();Aa();break;case 27:case 13:a.preventDefault();a.stopPropagation();C();a=b("#"+c+" li.selected").length;F=L.length!=a||0==a?!0:!1;N();O();K=null;break;case 16:A=!0;break;case 17:y=!0;break;default:47<=a.keyCode&&!1===r&&da()}if(!0===n)return!1;s("keydown")},ka=function(a){switch(a.keyCode){case 16:A=
!1;break;case 17:y=!1}if(!0===n)return!1;s("keyup")},qa=function(a){if(!0===n)return!1;s("dblclick")},ra=function(a){if(!0===n)return!1;s("mousemove")},sa=function(a){if(!0===n)return!1;a.preventDefault();s("mouseover")},ta=function(a){if(!0===n)return!1;a.preventDefault();s("mouseout")},ua=function(a){if(!0===n)return!1;s("mousedown")},va=function(a){if(!0===n)return!1;s("mouseup")},X=function(a,c){var f={byElement:!1,byJQuery:!1,hasEvent:!1};void 0!=b(a).prop("on"+c)&&(f.hasEvent=!0,f.byElement=
!0);var d=b(a).data("events");d&&d[c]&&(f.hasEvent=!0,f.byJQuery=!0);return f},D=function(a,c){if(0==d.disabledOptionEvents){var f=h(e).options[x(a)];if(!0===X(f,c).hasEvent){if(!0===X(f,c).byElement)f["on"+c]();if(!0===X(f,c).byJQuery)switch(c){case "keydown":case "keyup":break;default:b(f).trigger(c)}return!1}}},s=function(a){"function"==typeof d.on[a]&&d.on[a].apply(this,arguments);if(!0===P(a).hasEvent){if(!0===P(a).byElement)h(e)["on"+a]();else if(!0===P(a).byJQuery)switch(a){case "keydown":case "keyup":break;
default:b("#"+e).triggerHandler(a)}return!1}},Y=function(a){var c=m("postChildID");a=void 0!==a?a:b("#"+c+" li.selected");if(0<a.length){a=parseInt(b(a).position().top);var f=parseInt(b("#"+c).height());a>f&&(a=a+b("#"+c).scrollTop()-f/2,b("#"+c).animate({scrollTop:a},500))}},za=function(){function a(c){c+=1;return c>f.length||!0===b(f[c]).hasClass("enabled")?c:a(c)}var c=m("postChildID"),f=b("#"+c+" li:visible._msddli_"),d=b("#"+c+" li:visible.selected"),d=0==d.length?f[0]:d,d=b("#"+c+" li:visible._msddli_").index(d);
d<f.length-1&&(d=a(d),d<f.length&&(A&&r&&v||b("#"+c+" .selected").removeClass("selected"),b(f[d]).addClass("selected"),E(d),1==r&&N(),Y(b(f[d]))),r||Q())},Aa=function(){function a(c){c-=1;return 0>c||!0===b(e[c]).hasClass("enabled")?c:a(c)}var c=m("postChildID"),d=b("#"+c+" li:visible.selected"),e=b("#"+c+" li:visible._msddli_"),d=b("#"+c+" li:visible._msddli_").index(d[0]);0<=d&&(d=a(d),0<=d&&(A&&r&&v||b("#"+c+" .selected").removeClass("selected"),b(e[d]).addClass("selected"),E(d),1==r&&N(),0>=parseInt(b(e[d]).position().top+
b(e[d]).height())&&(d=b("#"+c).scrollTop()-b("#"+c).height()-b(e[d]).height(),b("#"+c).animate({scrollTop:d},500))),r||Q())},Q=function(){var a=m("postID"),c=m("postChildID"),f=b("#"+a).offset(),e=b("#"+a).height(),h=b(window).height(),l=b(window).scrollTop(),n=b("#"+c).height(),p=b("#"+a).height(),q=d.openDirection.toLowerCase();(h+l<Math.floor(n+e+f.top)||"alwaysup"==q)&&"alwaysdown"!=q?(p=n,b("#"+c).css({top:"-"+p+"px",display:"block",zIndex:d.zIndex}),"true"==d.roundedCorner&&b("#"+a).removeClass("borderRadius borderRadiusTp").addClass("borderRadiusBtm"),
p=b("#"+c).offset().top,-10>p&&(b("#"+c).css({top:parseInt(b("#"+c).css("top"))-p+20+l+"px",zIndex:d.zIndex}),"true"==d.roundedCorner&&b("#"+a).removeClass("borderRadiusBtm borderRadiusTp").addClass("borderRadius"))):(b("#"+c).css({top:p+"px",zIndex:d.zIndex}),"true"==d.roundedCorner&&b("#"+a).removeClass("borderRadius borderRadiusBtm").addClass("borderRadiusTp"));oa&&(c=M.indexOf("MSIE"),c=0<c?parseInt(M.substring(c+5,M.indexOf(".",c))):0,7>=c&&(b("div.ddcommon").css("zIndex",d.zIndex-10),b("#"+
a).css("zIndex",d.zIndex+5)))},V=function(a){if(!0===n)return!1;m("postID");a=m("postChildID");if(J)"mouseover"!==d.event&&C();else{J=!0;""!=msBeautify.oldDiv&&b("#"+msBeautify.oldDiv).css({display:"none"});msBeautify.oldDiv=a;b("#"+a+" li:hidden").show();Q();var c=d.animStyle;if(""==c||"none"==c)b("#"+a).css({display:"block"}),Y(),"function"==typeof d.on.open&&(a=z(),d.on.open(a.data,a.ui));else b("#"+a)[c]("fast",function(){Y();if("function"==typeof d.on.open){var a=z();d.on.open(a.data,a.ui)}});
U()}b("#searchSuggestions").removeClass("open")},C=function(a){J=!1;var c=m("postID");a=m("postChildID");if(!1===r||!0===d.enableCheckbox)b("#"+a).css({display:"none"}),"true"==d.roundedCorner&&b("#"+c).removeClass("borderRadiusTp borderRadiusBtm").addClass("borderRadius");O();"function"==typeof d.on.close&&(c=z(),d.on.close(c.data,c.ui));c=m("postTitleTextID");0<b("#"+c+":visible").length&&(b("#"+c+":visible").hide(),h(c).blur());u(u());b("#"+a).css({zIndex:1});E(h(e).selectedIndex)},Ba=function(){try{I=
b.extend(!0,{},h(e));for(var a in I)"function"!=typeof I[a]&&(l[a]=I[a])}catch(c){}l.selectedText=0<=h(e).selectedIndex?h(e).options[h(e).selectedIndex].text:"";l.version=msBeautify.version.msDropdown;l.author=msBeautify.author},la=function(a){if(null!=a&&"undefined"!=typeof a){var c=m("postChildID"),d=B(a),c=b("#"+c+" li._msddli_:eq("+a.index+")");return{data:d,ui:c,option:a,index:a.index}}return null},z=function(){var a=m("postChildID"),c=h(e),d,g;if(-1==c.selectedIndex)g=a=d=null,c=-1;else if(a=
b("#"+a+" li.selected"),1<a.length){var k=[];g=[];for(d=0;d<a.length;d++){var l=x(a[d]);k.push(l);g.push(c.options[l])}c=d=k}else g=c.options[c.selectedIndex],d=B(g),c=c.selectedIndex;return{data:d,ui:a,index:c,option:g}},E=function(a,c){var f=m("postTitleID"),g={};-1==a?(g.text="&nbsp;",g.className="",g.description="",g.image=""):"undefined"!=typeof a?(g=h(e).options[a],g=B(g)):g=c;b("#"+f).find(".ddlabel").html(g.text);h(f).className="ddTitleText "+g.className;""!=g.description?b("#"+f).find(".description").html(g.description).show():
b("#"+f).find(".description").html("").hide();var k=b("#"+f).find("img");0<k.length&&b(k).remove();""!=g.image&&d.showIcon&&(k=p("img",{src:g.image}),b("#"+f).prepend(k),""!=g.imagecss&&(k.className=g.imagecss+" "),""==g.description&&(k.className+="fnone"))},ma=function(a,b){l[a]=b},na=function(a,c,f){var g=m("postChildID"),k=!1;switch(a){case "add":var l=T(c||h(e).options[f]),k=3==arguments.length?f:b("#"+g+" li._msddli_").length-1;0>k||!k?b("#"+g+" ul").append(l):(g=b("#"+g+" li._msddli_")[k],b(g).before(l));
g=m("postChildID");b("#"+g).off("click");b("#"+g+" li.enabled").off("mouseenter");b("#"+g+" li.enabled").off("click");b("#"+g+" li.enabled").off("mouseover");b("#"+g+" li.enabled").off("mouseout");b("#"+g+" li.enabled").off("mousedown");b("#"+g+" li.enabled").off("mouseup");ba();null!=d.on.add&&d.on.add.apply(this,arguments);break;case "remove":k=b(b("#"+g+" li._msddli_")[f]).hasClass("selected"),b("#"+g+" li._msddli_:eq("+f+")").remove(),l=b("#"+g+" li.enabled"),1==k&&0<l.length&&(b(l[0]).addClass("selected"),
k=b("#"+g+" li._msddli_").index(l[0]),w(k)),0==l.length&&w(-1),b("#"+g+" li._msddli_").length<d.visibleRows&&!r&&u(-1),null!=d.on.remove&&d.on.remove.apply(this,arguments)}};this.act=function(){var a=arguments[0];Array.prototype.shift.call(arguments);switch(a){case "add":l.add.apply(this,arguments);break;case "remove":l.remove.apply(this,arguments);break;default:try{h(e)[a].apply(h(e),arguments)}catch(b){}}};this.add=function(){var a,c,d,g,k;k=arguments[0];"string"==typeof k?(a=k,opt=new Option(a,
a)):(a=k.text||"",c=k.value||a,d=k.title||"",g=k.image||"",k=k.description||"",opt=new Option(a,c),b(opt).data("description",k),b(opt).data("image",g),b(opt).data("title",d));arguments[0]=opt;h(e).add.apply(h(e),arguments);a=h(e).children;l.children=a;a=h(e).length;l.length=a;na("add",opt,arguments[1])};this.remove=function(a){h(e).remove(a);var b=h(e).children;l.children=b;b=h(e).length;l.length=b;na("remove",void 0,a)};this.set=function(a,c){if("undefined"==typeof a||"undefined"==typeof c)return!1;
a=a.toString();try{l[a]=c}catch(d){}switch(a){case "size":h(e)[a]=c;0==c&&(h(e).multiple=!1);r=1<h(e).size||1==h(e).multiple?!0:!1;W();break;case "multiple":h(e)[a]=c;r=1<h(e).size||1==h(e).multiple?!0:!1;v=h(e).multiple;W();l[a]=c;break;case "disabled":n=h(e)[a]=c;ga();break;case "selectedIndex":case "value":"selectedIndex"==a&&!0===$(c)?(b("#"+e+" option").prop("selected",!1),ia(c,!0),ha(c)):(h(e)[a]=c,ha(h(e).selectedIndex),w(h(e).selectedIndex));break;case "length":var g=m("postChildID");c<h(e).length&&
(h(e)[a]=c,0==c?(b("#"+g+" li._msddli_").remove(),w(-1)):(b("#"+g+" li._msddli_:gt("+(c-1)+")").remove(),0==b("#"+g+" li.selected").length&&b("#"+g+" li.enabled:eq(0)").addClass("selected")),l[a]=c,g=h(e).children,l.children=g);break;case "id":break;default:try{h(e)[a]=c,l[a]=c}catch(k){}}};this.get=function(a){return l[a]||h(e)[a]};this.visible=function(a){var c=m("postID");if(!0===a)b("#"+c).show();else if(!1===a)b("#"+c).hide();else return"none"==b("#"+c).css("display")?!1:!0};this.debug=function(a){msBeautify.debug(a)};
this.close=function(){C()};this.open=function(){V()};this.visibleRows=this.showRows=function(a){if("undefined"==typeof a||0==a)return!1;d.visibleRows=a;u(u())};this.on=function(a,c){b("#"+e).on(a,c)};this.off=function(a,c){b("#"+e).off(a,c)};this.addMyEvent=this.on;this.getData=function(){return z()};this.namedItem=function(){var a=h(e).namedItem.apply(h(e),arguments);return la(a)};this.item=function(){var a=h(e).item.apply(h(e),arguments);return la(a)};this.setIndexByValue=function(a){this.set("value",
a)};this.destroy=function(){m("postElementHolder");var a=m("postID");b("#"+a+", #"+a+" *").off();h(e).tabIndex=h(a).tabIndex;b("#"+a).remove();b("#"+e).parent().replaceWith(b("#"+e));b("#"+e).data("dd",null)};this.refresh=function(){w(h(e).selectedIndex)};(function(){pa();e.id||(e.id="msdrpdd"+msBeautify.counter++);e=e.id;l.element=e;d.mainCSS=b("#"+e).data("maincss")||d.mainCSS;d.visibleRows=b("#"+e).data("visiblerows")||d.visibleRows;0==b("#"+e).data("showicon")&&(d.showIcon=b("#"+e).data("showicon"));
d.useSprite=b("#"+e).data("usesprite")||d.useSprite;d.animStyle=b("#"+e).data("animstyle")||d.animStyle;d.event=b("#"+e).data("event")||d.event;d.openDirection=b("#"+e).data("opendirection")||d.openDirection;d.jsonTitle=b("#"+e).data("jsontitle")||d.jsonTitle;d.disabledOpacity=b("#"+e).data("disabledopacity")||d.disabledOpacity;d.childWidth=b("#"+e).data("childwidth")||d.childWidth;d.enableCheckbox=b("#"+e).data("enablecheckbox")||d.enableCheckbox;d.checkboxNameSuffix=b("#"+e).data("checkboxnamesuffix")||
d.checkboxNameSuffix;d.append=b("#"+e).data("append")||d.append;d.prepend=b("#"+e).data("prepend")||d.prepend;d.reverseMode=b("#"+e).data("reversemode")||d.reverseMode;d.roundedCorner=b("#"+e).data("roundedcorner")||d.roundedCorner;d.enableAutoFilter=b("#"+e).data("enableautofilter")||d.enableAutoFilter;d.reverseMode=d.reverseMode.toString();d.roundedCorner=d.roundedCorner.toString();d.enableAutoFilter=d.enableAutoFilter.toString();n=h(e).disabled;"true"===d.enableCheckbox.toString()&&(h(e).multiple=
!0,d.enableCheckbox=!0);if(r=1<h(e).size||1==h(e).multiple?!0:!1)v=h(e).multiple;Ba();ya();ma("uiData",z());ma("selectedOptions",b("#"+e+" option:selected"));var a=m("postChildID");L=b("#"+a+" li.selected");if("true"===d.reverseMode)b("#"+e).on("change",function(){w(this.selectedIndex)});h(e).refresh=function(a){b("#"+e).msDropdown().data("dd").refresh()}})()}msBeautify={version:{msDropdown:"3.5.2"},author:"Marghoob Suleman",counter:20,debug:function(e){!1!==e?b(".ddOutOfVision").css({height:"auto",
position:"relative"}):b(".ddOutOfVision").css({height:"0px",position:"absolute"})},oldDiv:"",create:function(e,d,l){var H;switch((l||"dropdown").toLowerCase()){case "dropdown":case "select":H=b(e).msDropdown(d).data("dd")}return H}};b.msDropDown={};b.msDropdown={};b.extend(!0,b.msDropDown,msBeautify);b.extend(!0,b.msDropdown,msBeautify);void 0===b.fn.prop&&(b.fn.prop=b.fn.attr);void 0===b.fn.on&&(b.fn.on=b.fn.bind,b.fn.off=b.fn.unbind);b.expr[":"].Contains="function"===typeof b.expr.createPseudo?
b.expr.createPseudo(function(e){return function(d){return 0<=b(d).text().toUpperCase().indexOf(e.toUpperCase())}}):function(e,d,l){return 0<=b(e).text().toUpperCase().indexOf(l[3].toUpperCase())};b.fn.extend({msDropDown:function(e){return this.each(function(){if(!b(this).data("dd")){var d=new R(this,e);b(this).data("dd",d)}})}});b.fn.msDropdown=b.fn.msDropDown})(jQuery);